CREATE TABLE IF NOT EXISTS DataTable(
  ROW_ID       INTEGER,
  INT_TYPE     INTEGER,
  LONG_TYPE    BIGINT,
  FLOAT_TYPE   FLOAT,
  DOUBLE_TYPE  DOUBLE,
  BOOLEAN_TYPE BOOLEAN,
  STRING_TYPE  VARCHAR(50),
  DECIMAL_TYPE DECIMAL(20, 2),
  PRIMARY KEY (ROW_ID)
);

INSERT INTO DataTable (ROW_ID, INT_TYPE, LONG_TYPE, FLOAT_TYPE, DOUBLE_TYPE, BOOLEAN_TYPE, STRING_TYPE, DECIMAL_TYPE)
  VALUES(1, 1, 9223372036854774807, 123.34, 2139095039, TRUE, 'Hello', 23.45);

INSERT INTO DataTable (ROW_ID) VALUES (2);
