// This is an autogenerated file. Do not edit. Run 'npm run gen-models' to generate.
import * as Ballerina from "./models";

export interface Visitor {
  beginVisitCompilationUnit?(node: Ballerina.CompilationUnit): void;
  endVisitCompilationUnit?(node: Ballerina.CompilationUnit): void;

  beginVisitImport?(node: Ballerina.Import): void;
  endVisitImport?(node: Ballerina.Import): void;

  beginVisitIdentifier?(node: Ballerina.Identifier): void;
  endVisitIdentifier?(node: Ballerina.Identifier): void;

  beginVisitTypeDefinition?(node: Ballerina.TypeDefinition): void;
  endVisitTypeDefinition?(node: Ballerina.TypeDefinition): void;

  beginVisitObjectType?(node: Ballerina.ObjectType): void;
  endVisitObjectType?(node: Ballerina.ObjectType): void;

  beginVisitFunction?(node: Ballerina.Function): void;
  endVisitFunction?(node: Ballerina.Function): void;

  beginVisitValueType?(node: Ballerina.ValueType): void;
  endVisitValueType?(node: Ballerina.ValueType): void;

  beginVisitVariable?(node: Ballerina.Variable): void;
  endVisitVariable?(node: Ballerina.Variable): void;

  beginVisitBlock?(node: Ballerina.Block): void;
  endVisitBlock?(node: Ballerina.Block): void;

  beginVisitReturn?(node: Ballerina.Return): void;
  endVisitReturn?(node: Ballerina.Return): void;

  beginVisitBinaryExpr?(node: Ballerina.BinaryExpr): void;
  endVisitBinaryExpr?(node: Ballerina.BinaryExpr): void;

  beginVisitSimpleVariableRef?(node: Ballerina.SimpleVariableRef): void;
  endVisitSimpleVariableRef?(node: Ballerina.SimpleVariableRef): void;

  beginVisitLiteral?(node: Ballerina.Literal): void;
  endVisitLiteral?(node: Ballerina.Literal): void;

  beginVisitUserDefinedType?(node: Ballerina.UserDefinedType): void;
  endVisitUserDefinedType?(node: Ballerina.UserDefinedType): void;

  beginVisitIf?(node: Ballerina.If): void;
  endVisitIf?(node: Ballerina.If): void;

  beginVisitAssignment?(node: Ballerina.Assignment): void;
  endVisitAssignment?(node: Ballerina.Assignment): void;

  beginVisitFieldBasedAccessExpr?(node: Ballerina.FieldBasedAccessExpr): void;
  endVisitFieldBasedAccessExpr?(node: Ballerina.FieldBasedAccessExpr): void;

  beginVisitBracedTupleExpr?(node: Ballerina.BracedTupleExpr): void;
  endVisitBracedTupleExpr?(node: Ballerina.BracedTupleExpr): void;

  beginVisitVariableDef?(node: Ballerina.VariableDef): void;
  endVisitVariableDef?(node: Ballerina.VariableDef): void;

  beginVisitTypeInitExpr?(node: Ballerina.TypeInitExpr): void;
  endVisitTypeInitExpr?(node: Ballerina.TypeInitExpr): void;

  beginVisitExpressionStatement?(node: Ballerina.ExpressionStatement): void;
  endVisitExpressionStatement?(node: Ballerina.ExpressionStatement): void;

  beginVisitInvocation?(node: Ballerina.Invocation): void;
  endVisitInvocation?(node: Ballerina.Invocation): void;

  beginVisitFunctionType?(node: Ballerina.FunctionType): void;
  endVisitFunctionType?(node: Ballerina.FunctionType): void;

  beginVisitLambda?(node: Ballerina.Lambda): void;
  endVisitLambda?(node: Ballerina.Lambda): void;

  beginVisitArrowExpr?(node: Ballerina.ArrowExpr): void;
  endVisitArrowExpr?(node: Ballerina.ArrowExpr): void;

  beginVisitArrayType?(node: Ballerina.ArrayType): void;
  endVisitArrayType?(node: Ballerina.ArrayType): void;

  beginVisitArrayLiteralExpr?(node: Ballerina.ArrayLiteralExpr): void;
  endVisitArrayLiteralExpr?(node: Ballerina.ArrayLiteralExpr): void;

  beginVisitAnnotationAttachment?(node: Ballerina.AnnotationAttachment): void;
  endVisitAnnotationAttachment?(node: Ballerina.AnnotationAttachment): void;

  beginVisitRecordLiteralExpr?(node: Ballerina.RecordLiteralExpr): void;
  endVisitRecordLiteralExpr?(node: Ballerina.RecordLiteralExpr): void;

  beginVisitRecordLiteralKeyValue?(node: Ballerina.RecordLiteralKeyValue): void;
  endVisitRecordLiteralKeyValue?(node: Ballerina.RecordLiteralKeyValue): void;

  beginVisitIndexBasedAccessExpr?(node: Ballerina.IndexBasedAccessExpr): void;
  endVisitIndexBasedAccessExpr?(node: Ballerina.IndexBasedAccessExpr): void;

  beginVisitCompoundAssignment?(node: Ballerina.CompoundAssignment): void;
  endVisitCompoundAssignment?(node: Ballerina.CompoundAssignment): void;

  beginVisitCheckExpr?(node: Ballerina.CheckExpr): void;
  endVisitCheckExpr?(node: Ballerina.CheckExpr): void;

  beginVisitTypeConversionExpr?(node: Ballerina.TypeConversionExpr): void;
  endVisitTypeConversionExpr?(node: Ballerina.TypeConversionExpr): void;

  beginVisitUnaryExpr?(node: Ballerina.UnaryExpr): void;
  endVisitUnaryExpr?(node: Ballerina.UnaryExpr): void;

  beginVisitEndpoint?(node: Ballerina.Endpoint): void;
  endVisitEndpoint?(node: Ballerina.Endpoint): void;

  beginVisitConstrainedType?(node: Ballerina.ConstrainedType): void;
  endVisitConstrainedType?(node: Ballerina.ConstrainedType): void;

  beginVisitBuiltInRefType?(node: Ballerina.BuiltInRefType): void;
  endVisitBuiltInRefType?(node: Ballerina.BuiltInRefType): void;

  beginVisitUnionTypeNode?(node: Ballerina.UnionTypeNode): void;
  endVisitUnionTypeNode?(node: Ballerina.UnionTypeNode): void;

  beginVisitAwaitExpr?(node: Ballerina.AwaitExpr): void;
  endVisitAwaitExpr?(node: Ballerina.AwaitExpr): void;

  beginVisitMatch?(node: Ballerina.Match): void;
  endVisitMatch?(node: Ballerina.Match): void;

  beginVisitMatchPatternClause?(node: Ballerina.MatchPatternClause): void;
  endVisitMatchPatternClause?(node: Ballerina.MatchPatternClause): void;

  beginVisitWorker?(node: Ballerina.Worker): void;
  endVisitWorker?(node: Ballerina.Worker): void;

  beginVisitWorkerSend?(node: Ballerina.WorkerSend): void;
  endVisitWorkerSend?(node: Ballerina.WorkerSend): void;

  beginVisitWorkerReceive?(node: Ballerina.WorkerReceive): void;
  endVisitWorkerReceive?(node: Ballerina.WorkerReceive): void;

  beginVisitWhile?(node: Ballerina.While): void;
  endVisitWhile?(node: Ballerina.While): void;

  beginVisitService?(node: Ballerina.Service): void;
  endVisitService?(node: Ballerina.Service): void;

  beginVisitResource?(node: Ballerina.Resource): void;
  endVisitResource?(node: Ballerina.Resource): void;

  beginVisitMatchExpression?(node: Ballerina.MatchExpression): void;
  endVisitMatchExpression?(node: Ballerina.MatchExpression): void;

  beginVisitMatchExpressionPatternClause?(
    node: Ballerina.MatchExpressionPatternClause,
  ): void;
  endVisitMatchExpressionPatternClause?(
    node: Ballerina.MatchExpressionPatternClause,
  ): void;

  beginVisitNamedArgsExpr?(node: Ballerina.NamedArgsExpr): void;
  endVisitNamedArgsExpr?(node: Ballerina.NamedArgsExpr): void;

  beginVisitTupleTypeNode?(node: Ballerina.TupleTypeNode): void;
  endVisitTupleTypeNode?(node: Ballerina.TupleTypeNode): void;

  beginVisitThrow?(node: Ballerina.Throw): void;
  endVisitThrow?(node: Ballerina.Throw): void;

  beginVisitTry?(node: Ballerina.Try): void;
  endVisitTry?(node: Ballerina.Try): void;

  beginVisitTupleDestructure?(node: Ballerina.TupleDestructure): void;
  endVisitTupleDestructure?(node: Ballerina.TupleDestructure): void;

  beginVisitCatch?(node: Ballerina.Catch): void;
  endVisitCatch?(node: Ballerina.Catch): void;

  beginVisitXmlElementLiteral?(node: Ballerina.XmlElementLiteral): void;
  endVisitXmlElementLiteral?(node: Ballerina.XmlElementLiteral): void;

  beginVisitXmlQname?(node: Ballerina.XmlQname): void;
  endVisitXmlQname?(node: Ballerina.XmlQname): void;

  beginVisitRecordType?(node: Ballerina.RecordType): void;
  endVisitRecordType?(node: Ballerina.RecordType): void;

  beginVisitRestArgsExpr?(node: Ballerina.RestArgsExpr): void;
  endVisitRestArgsExpr?(node: Ballerina.RestArgsExpr): void;

  beginVisitForeach?(node: Ballerina.Foreach): void;
  endVisitForeach?(node: Ballerina.Foreach): void;

  beginVisitTable?(node: Ballerina.Table): void;
  endVisitTable?(node: Ballerina.Table): void;

  beginVisitMarkdownDocumentation?(node: Ballerina.MarkdownDocumentation): void;
  endVisitMarkdownDocumentation?(node: Ballerina.MarkdownDocumentation): void;

  beginVisitDocumentationDescription?(
    node: Ballerina.DocumentationDescription,
  ): void;
  endVisitDocumentationDescription?(
    node: Ballerina.DocumentationDescription,
  ): void;

  beginVisitDocumentationParameter?(
    node: Ballerina.DocumentationParameter,
  ): void;
  endVisitDocumentationParameter?(node: Ballerina.DocumentationParameter): void;

  beginVisitElvisExpr?(node: Ballerina.ElvisExpr): void;
  endVisitElvisExpr?(node: Ballerina.ElvisExpr): void;

  beginVisitForkJoin?(node: Ballerina.ForkJoin): void;
  endVisitForkJoin?(node: Ballerina.ForkJoin): void;

  beginVisitStringTemplateLiteral?(node: Ballerina.StringTemplateLiteral): void;
  endVisitStringTemplateLiteral?(node: Ballerina.StringTemplateLiteral): void;

  beginVisitDone?(node: Ballerina.Done): void;
  endVisitDone?(node: Ballerina.Done): void;

  beginVisitForever?(node: Ballerina.Forever): void;
  endVisitForever?(node: Ballerina.Forever): void;

  beginVisitStreamingQuery?(node: Ballerina.StreamingQuery): void;
  endVisitStreamingQuery?(node: Ballerina.StreamingQuery): void;

  beginVisitStreamingInput?(node: Ballerina.StreamingInput): void;
  endVisitStreamingInput?(node: Ballerina.StreamingInput): void;

  beginVisitWindowClause?(node: Ballerina.WindowClause): void;
  endVisitWindowClause?(node: Ballerina.WindowClause): void;

  beginVisitWhere?(node: Ballerina.Where): void;
  endVisitWhere?(node: Ballerina.Where): void;

  beginVisitStreamAction?(node: Ballerina.StreamAction): void;
  endVisitStreamAction?(node: Ballerina.StreamAction): void;

  beginVisitSelectClause?(node: Ballerina.SelectClause): void;
  endVisitSelectClause?(node: Ballerina.SelectClause): void;

  beginVisitGroupBy?(node: Ballerina.GroupBy): void;
  endVisitGroupBy?(node: Ballerina.GroupBy): void;

  beginVisitHaving?(node: Ballerina.Having): void;
  endVisitHaving?(node: Ballerina.Having): void;

  beginVisitSelectExpression?(node: Ballerina.SelectExpression): void;
  endVisitSelectExpression?(node: Ballerina.SelectExpression): void;

  beginVisitTernaryExpr?(node: Ballerina.TernaryExpr): void;
  endVisitTernaryExpr?(node: Ballerina.TernaryExpr): void;

  beginVisitPatternClause?(node: Ballerina.PatternClause): void;
  endVisitPatternClause?(node: Ballerina.PatternClause): void;

  beginVisitPatternStreamingInput?(node: Ballerina.PatternStreamingInput): void;
  endVisitPatternStreamingInput?(node: Ballerina.PatternStreamingInput): void;

  beginVisitPatternStreamingEdgeInput?(
    node: Ballerina.PatternStreamingEdgeInput,
  ): void;
  endVisitPatternStreamingEdgeInput?(
    node: Ballerina.PatternStreamingEdgeInput,
  ): void;

  beginVisitBreak?(node: Ballerina.Break): void;
  endVisitBreak?(node: Ballerina.Break): void;

  beginVisitIntRangeExpr?(node: Ballerina.IntRangeExpr): void;
  endVisitIntRangeExpr?(node: Ballerina.IntRangeExpr): void;

  beginVisitJoinStreamingInput?(node: Ballerina.JoinStreamingInput): void;
  endVisitJoinStreamingInput?(node: Ballerina.JoinStreamingInput): void;

  beginVisitXmlAttribute?(node: Ballerina.XmlAttribute): void;
  endVisitXmlAttribute?(node: Ballerina.XmlAttribute): void;

  beginVisitXmlQuotedString?(node: Ballerina.XmlQuotedString): void;
  endVisitXmlQuotedString?(node: Ballerina.XmlQuotedString): void;

  beginVisitXmlCommentLiteral?(node: Ballerina.XmlCommentLiteral): void;
  endVisitXmlCommentLiteral?(node: Ballerina.XmlCommentLiteral): void;

  beginVisitTransaction?(node: Ballerina.Transaction): void;
  endVisitTransaction?(node: Ballerina.Transaction): void;

  beginVisitAbort?(node: Ballerina.Abort): void;
  endVisitAbort?(node: Ballerina.Abort): void;

  beginVisitRetry?(node: Ballerina.Retry): void;
  endVisitRetry?(node: Ballerina.Retry): void;

  beginVisitLock?(node: Ballerina.Lock): void;
  endVisitLock?(node: Ballerina.Lock): void;

  beginVisitFiniteTypeNode?(node: Ballerina.FiniteTypeNode): void;
  endVisitFiniteTypeNode?(node: Ballerina.FiniteTypeNode): void;

  beginVisitTableColumn?(node: Ballerina.TableColumn): void;
  endVisitTableColumn?(node: Ballerina.TableColumn): void;

  beginVisitTableQueryExpression?(node: Ballerina.TableQueryExpression): void;
  endVisitTableQueryExpression?(node: Ballerina.TableQueryExpression): void;

  beginVisitTableQuery?(node: Ballerina.TableQuery): void;
  endVisitTableQuery?(node: Ballerina.TableQuery): void;

  beginVisitOrderBy?(node: Ballerina.OrderBy): void;
  endVisitOrderBy?(node: Ballerina.OrderBy): void;

  beginVisitOrderByVariable?(node: Ballerina.OrderByVariable): void;
  endVisitOrderByVariable?(node: Ballerina.OrderByVariable): void;

  beginVisitNext?(node: Ballerina.Next): void;
  endVisitNext?(node: Ballerina.Next): void;

  beginVisitXmlAttributeAccessExpr?(
    node: Ballerina.XmlAttributeAccessExpr,
  ): void;
  endVisitXmlAttributeAccessExpr?(node: Ballerina.XmlAttributeAccessExpr): void;

  beginVisitXmlns?(node: Ballerina.Xmlns): void;
  endVisitXmlns?(node: Ballerina.Xmlns): void;

  beginVisitXmlTextLiteral?(node: Ballerina.XmlTextLiteral): void;
  endVisitXmlTextLiteral?(node: Ballerina.XmlTextLiteral): void;

  beginVisitXmlPiLiteral?(node: Ballerina.XmlPiLiteral): void;
  endVisitXmlPiLiteral?(node: Ballerina.XmlPiLiteral): void;
}
