<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>name</key>
    <string>Ballerina</string>
    <key>scopeName</key>
    <string>source.ballerina</string>
    <key>fileTypes</key>
    <array>
      <string>bal</string>
    </array>
    <key>uuid</key>
    <string>c01f5512-489a-41bd-ba5d-caf4b55ae3b3</string>
    <key>variables</key>
    <dict>
      <key>identifier</key>
      <string>({{letter}}({{letterOrDigit}})*)|(\^"{{identifierLiteralChar}}+")</string>
      <key>letter</key>
      <string>[a-zA-Z_]</string>
      <key>letterOrDigit</key>
      <string>[a-zA-Z0-9_]</string>
      <key>identifierLiteralChar</key>
      <string>([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])</string>
    </dict>
    <key>patterns</key>
    <array>
      <dict>
        <key>include</key>
        <string>#publicKeyword</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#functionDec</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#serviceDec</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#documentationDef</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#typeDef</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#objectDec</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#annotationDec</string>
      </dict>
      <dict>
        <key>include</key>
        <string>#code</string>
      </dict>
    </array>
    <key>repository</key>
    <dict>
      <key>annotationDec</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>@([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
            <key>name</key>
            <string>storage.type.annotation.ballerina</string>
          </dict>
        </array>
      </dict>
      <key>booleans</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b(true|false)\b</string>
            <key>name</key>
            <string>constant.language.boolean.ballerina</string>
          </dict>
        </array>
      </dict>
      <key>butExp</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(but)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#butExpBody</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>butExpBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>\b([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")\b</string>
                <key>name</key>
                <string>storage.type.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#butClause</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>butClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>=&gt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>,</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>comment</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>comment.ballerina</string>
            <key>match</key>
            <string>\/\/.*</string>
          </dict>
        </array>
      </dict>
      <key>continuedType</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>[|,:]</string>
            <key>end</key>
            <string>\b(([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+"))\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>defaultValue</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>[=:]</string>
            <key>end</key>
            <string>(?=[,)])</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>documentationDef</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(documentation|deprecated)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#documentationBody</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>documentationBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>(P|R|T|F|V)({{)(.+)(}})</string>
                <key>captures</key>
                <dict>
                  <key>1</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.ballerina.documentation</string>
                  </dict>
                  <key>2</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.ballerina.documentation</string>
                  </dict>
                  <key>3</key>
                  <dict>
                    <key>name</key>
                    <string>variable.parameter.ballerina.documentation</string>
                  </dict>
                  <key>4</key>
                  <dict>
                    <key>name</key>
                    <string>keyword.other.ballerina.documentation</string>
                  </dict>
                </dict>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.block.code.ballerina.documentation</string>
                <key>begin</key>
                <string>\```</string>
                <key>end</key>
                <string>\```</string>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.block.code.ballerina.documentation</string>
                <key>begin</key>
                <string>\``</string>
                <key>end</key>
                <string>\``</string>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.block.code.ballerina.documentation</string>
                <key>begin</key>
                <string>\`</string>
                <key>end</key>
                <string>\`</string>
              </dict>
              <dict>
                <key>name</key>
                <string>comment.block.ballerina.documentation</string>
                <key>match</key>
                <string>.</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionDec</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(function)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionReceiver</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionParameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionReturns</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionName</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionBody</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionName</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function.ballerina</string>
            <key>match</key>
            <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
          </dict>
        </array>
      </dict>
      <key>functionParameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#varDefStatement</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#defaultValue</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionReceiver</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#varDefStatement</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>functionReturns</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\breturns\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\{)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
                <key>name</key>
                <string>storage.type.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>identifiers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
            <key>name</key>
            <string>variable.other.ballerina</string>
          </dict>
        </array>
      </dict>
      <key>maps</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>matchStatementPatternClause</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>=&gt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>((?&lt;=\})|;|,)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#functionBody</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>matchStatement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(match)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
                <key>name</key>
                <string>variable.parameter.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#matchStatementBody</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>matchStatementBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#varDefStatement</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#matchStatementPatternClause</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>numbers</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\b[0-9]+\b</string>
            <key>name</key>
            <string>constant.numeric.decimal.ballerina</string>
          </dict>
        </array>
      </dict>
      <key>objectBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#varDefBlock</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#objectInitDec</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionDec</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>objectDec</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(object)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#objectBody</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>objectInitBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>objectInitDec</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(new)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#objectInitParameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#objectInitBody</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>objectInitParameters</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#types</string>
              </dict>
              <dict>
                <key>match</key>
                <string>\b(([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+"))\b</string>
                <key>name</key>
                <string>variable.parameter.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#defaultValue</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>paranthesised</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\(</string>
            <key>end</key>
            <string>\)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>paranthesisedBracket</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\[</string>
            <key>end</key>
            <string>\]</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>publicKeyword</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>match</key>
            <string>\bpublic\b</string>
            <key>name</key>
            <string>keyword.ballerina</string>
          </dict>
        </array>
      </dict>
      <key>resourceBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#code</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>resourceDef</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+"))\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionParameters</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#resourceBody</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>serviceBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>end</key>
            <string>\}</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#documentationDef</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#annotationDec</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#resourceDef</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>serviceDec</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(service)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#serviceReceiver</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#serviceEndpointAttachments</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#serviceName</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#serviceBody</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>serviceEndpointAttachments</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>bind</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?=\{)</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
                <key>name</key>
                <string>variable.parameter.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>serviceName</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>entity.name.function.ballerina</string>
            <key>match</key>
            <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
          </dict>
        </array>
      </dict>
      <key>serviceReceiver</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>&lt;</string>
            <key>end</key>
            <string>&gt;</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.begin.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.parameters.end.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>match</key>
                <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
                <key>name</key>
                <string>storage.type.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>strings</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>string.quoted.double.ballerina</string>
            <key>begin</key>
            <string>\"</string>
            <key>end</key>
            <string>\"</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.begin.ballerina</string>
              </dict>
            </dict>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.string.end.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>name</key>
                <string>constant.character.escape.ballerina</string>
                <key>match</key>
                <string>\\.</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>typeDef</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(type)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\b(([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+"))\b</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>entity.name.function.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#objectDec</string>
              </dict>
              <dict>
                <key>match</key>
                <string>([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+")</string>
                <key>name</key>
                <string>entity.name.function.ballerina</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>varDefBlock</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(private|public)\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>keyword.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>(?&lt;=\})</string>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#varDefBlockBody</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#functionDec</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>varDefBlockBody</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\{</string>
            <key>beginCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\}</string>
            <key>endCaptures</key>
            <dict>
              <key>0</key>
              <dict>
                <key>name</key>
                <string>punctuation.definition.block.ballerina.documentation</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#varDefStatement</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>varDefStatement</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>begin</key>
            <string>\b(([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+"))\b</string>
            <key>beginCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>storage.type.ballerina</string>
              </dict>
            </dict>
            <key>end</key>
            <string>\b(([a-zA-Z_]([a-zA-Z0-9_])*)|(\^"([^|"\\\f\n\r\t]|\\\\[btnfr]|\\[|"\\/])+"))\b|(?==&gt;)</string>
            <key>endCaptures</key>
            <dict>
              <key>1</key>
              <dict>
                <key>name</key>
                <string>variable.parameter.ballerina</string>
              </dict>
            </dict>
            <key>patterns</key>
            <array>
              <dict>
                <key>include</key>
                <string>#continuedType</string>
              </dict>
              <dict>
                <key>include</key>
                <string>#comment</string>
              </dict>
            </array>
          </dict>
        </array>
      </dict>
      <key>types</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>storage.type.ballerina</string>
            <key>match</key>
            <string>\b(boolean|int|float|string|var|any|datatable|table|blob)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.ballerina</string>
            <key>match</key>
            <string>\b(map|exception|json|xml|xmlns|error)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>storage.type.siddhi.ballerina</string>
            <key>match</key>
            <string>\b(stream|streamlet|aggregation)\b</string>
          </dict>
        </array>
      </dict>
      <key>keywords</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>name</key>
            <string>keyword.control.ballerina</string>
            <key>match</key>
            <string>\b(if|else|iterator|try|catch|finally|fork|join|all|some|while|foreach|in|throw|return|returns|break|timeout|transaction|aborted|abort|committed|failed|retries|next|bind|with|lengthof|typeof|enum)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.ballerina</string>
            <key>match</key>
            <string>\b(import|version|public|private|attach|as|native|documentation|lock)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.siddhi.ballerina</string>
            <key>match</key>
            <string>\b(from|on|select|group|by|having|order|where|followed|insert|into|update|delete|set|for|window|query)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.ballerina</string>
            <key>match</key>
            <string>\b(annotation|package|type|typedesc|connector|function|resource|service|action|worker|struct|transformer|endpoint|object)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.other.ballerina</string>
            <key>match</key>
            <string>\b(const|true|false|reply|create|parameter)\b</string>
          </dict>
          <dict>
            <key>name</key>
            <string>keyword.operator.ballerina</string>
            <key>match</key>
            <string>(!|%|\+|\-|~=|==|=|!=|&lt;|&gt;|&amp;&amp;|\|\|)</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#types</string>
          </dict>
        </array>
      </dict>
      <key>code</key>
      <dict>
        <key>patterns</key>
        <array>
          <dict>
            <key>include</key>
            <string>#booleans</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#keywords</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#strings</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#maps</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#paranthesised</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#paranthesisedBracket</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#numbers</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#comment</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#matchStatement</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#butExp</string>
          </dict>
          <dict>
            <key>include</key>
            <string>#identifiers</string>
          </dict>
        </array>
      </dict>
    </dict>
  </dict>
</plist>