// This is an empty Ballerina class autogenerated to represent the `java.lang.Character$Subset` Java class.
//
// If you need the implementation of this class generated, please use the following command.
//
// $ bal bindgen [(-cp|--classpath) <classpath>...] [(-o|--output) <output>] (<class-name>...)
//
// E.g. $ bal bindgen java.lang.Character\$Subset

import ballerina/jballerina.java;

# Ballerina class mapping for the Java `java.lang.Character$Subset` class.
@java:Binding {'class: "java.lang.Character$Subset"}
distinct class Subset {

    *java:JObject;

    # The `handle` field that stores the reference to the `java.lang.Character$Subset` object.
    public handle jObj;

    # The init function of the Ballerina class mapping the `java.lang.Character$Subset` Java class.
    #
    # + obj - The `handle` value containing the Java reference of the object.
    function init(handle obj) {
        self.jObj = obj;
    }

    # The function to retrieve the string representation of the Ballerina class mapping the `java.lang.Character$Subset` Java class.
    #
    # + return - The `string` form of the Java object instance.
    function toString() returns string {
        return java:toString(self.jObj) ?: "null";
    }
}
