# TestGrid Test Configuration Parameters
version: '0.9'
emailToList: "manurip@wso2.com,vijithae@wso2.com,ballerina-group@wso2.com"
infrastructureConfig:
  infrastructureProvider: SHELL
  containerOrchestrationEngine: K8S
  includes:
    - Ubuntu-18.04
    - MySQL-5.7
    - OracleJDK-8
  provisioners:
  - name: 'infrastructure-creation'
    remoteRepository: "git@github.com:ballerina-platform/aws-ballerina.git"
    remoteBranch: "use-existing-cluster"
    description: 'Creates infrastructure for ballerina scenario tests'
    scripts:
      - name: 'infrastructure-creation'
        description: 'Since an existing cluster is used, only a log is printed by the infrastructure script'
        type: SHELL
        phase: CREATE
        file: bbg/common_infra.sh
      - name: destroy
        description: 'Deletes all the k8s resources in the namespace used for this job'
        file: bbg/common-cleanup.sh
        type: SHELL
        phase: DESTROY
deploymentConfig:
  deploymentPatterns:
    - name: 'data-backed-service-deployment'
      description: 'Creates the deployment for the data-backed-service BBG'
      remoteRepository: "https://github.com/ballerina-platform/ballerina-lang.git"
      remoteBranch: "ballerina-scenarios-cleaned"
      dir: .
      scripts:
        - name: 'data-backed-service-deployment'
          type: SHELL
          file: product-scenarios/test-grid-scripts/bbg/data/deployment-data-backed-service.sh
          inputParameters:
            BallerinaVersion: "0.990.3"
            isDebugEnabled: "false"
scenarioConfigs:
- testType: TESTNG
  remoteRepository: "https://github.com/ballerina-platform/ballerina-lang.git"
  remoteBranch: "ballerina-scenarios-cleaned"
  name: "data-backed-service-tests"
  description: "Runs tests for the data-backed-service BBG"
  file: product-scenarios/test-grid-scripts/bbg/data/test-data-backed-service.sh
  inputParameters:
    BallerinaVersion: "0.990.3"
    isDebugEnabled: "false"
