import { Statement } from "./statement";

export * from "./function";
export * from "./service";
export * from "./svg-canvas";
export * from "./block";
export * from "./while";
export * from "./if";
export * from "./match";
export * from "./foreach";
export * from "./return";
export * from "./type-definition";
export * from "./worker-send";
export { Statement as ExpressionStatement};
export { Statement as VariableDef};
export { Statement as Assignment};
export { Statement as CompoundAssignment};
export { Statement as Panic};
export { Statement as Break};
export { Statement as Continue};
