public type Account record {
    string  Id?;
    boolean  IsDeleted?;
    string?  MasterRecordId?;
    string  Name?;
    anydata?  Type = ();
    string?  ParentId = ();
    string?  BillingStreet = ();
    string?  BillingCity = ();
    string?  BillingState = ();
    string?  BillingPostalCode = ();
    string?  BillingCountry = ();
    float?  BillingLatitude = ();
    float?  BillingLongitude = ();
    anydata?  BillingGeocodeAccuracy = ();
    anydata?  BillingAddress?;
    string?  ShippingStreet = ();
    string?  ShippingCity = ();
    string?  ShippingState = ();
    string?  ShippingPostalCode = ();
    string?  ShippingCountry = ();
    float?  ShippingLatitude = ();
    float?  ShippingLongitude = ();
    anydata?  ShippingGeocodeAccuracy = ();
    anydata?  ShippingAddress?;
    string?  Phone = ();
    string?  Fax = ();
    string?  AccountNumber = ();
    string?  Website = ();
    string?  PhotoUrl?;
    string?  Sic = ();
    anydata?  Industry = ();
    float?  AnnualRevenue = ();
    int?  NumberOfEmployees = ();
    anydata?  Ownership = ();
    string?  TickerSymbol = ();
    string?  Description = ();
    anydata?  Rating = ();
    string?  Site = ();
    string  OwnerId?;
    string  CreatedDate?;
    string  CreatedById?;
    string  LastModifiedDate?;
    string  LastModifiedById?;
    string  SystemModstamp?;
    string?  LastActivityDate?;
    string?  LastViewedDate?;
    string?  LastReferencedDate?;
    string?  Jigsaw = ();
    string?  JigsawCompanyId?;
    anydata?  CleanStatus = ();
    anydata?  AccountSource = ();
    string?  DunsNumber = ();
    string?  Tradestyle = ();
    string?  NaicsCode = ();
    string?  NaicsDesc = ();
    string?  YearStarted = ();
    string?  SicDesc = ();
    string?  DandbCompanyId = ();
    string?  OperatingHoursId = ();
    anydata?  CustomerPriority__c = ();
    anydata?  SLA__c = ();
    anydata?  Active__c = ();
    float?  NumberofLocations__c = ();
    anydata?  UpsellOpportunity__c = ();
    string?  SLASerialNumber__c = ();
    string?  SLAExpirationDate__c = ();
};
