public type Contact record {
    string  Id?;
    boolean  IsDeleted?;
    string?  MasterRecordId?;
    string?  AccountId = ();
    string  LastName?;
    string?  FirstName = ();
    anydata?  Salutation = ();
    string  Name?;
    string?  OtherStreet = ();
    string?  OtherCity = ();
    string?  OtherState = ();
    string?  OtherPostalCode = ();
    string?  OtherCountry = ();
    float?  OtherLatitude = ();
    float?  OtherLongitude = ();
    anydata?  OtherGeocodeAccuracy = ();
    anydata?  OtherAddress?;
    string?  MailingStreet = ();
    string?  MailingCity = ();
    string?  MailingState = ();
    string?  MailingPostalCode = ();
    string?  MailingCountry = ();
    float?  MailingLatitude = ();
    float?  MailingLongitude = ();
    anydata?  MailingGeocodeAccuracy = ();
    anydata?  MailingAddress?;
    string?  Phone = ();
    string?  Fax = ();
    string?  MobilePhone = ();
    string?  HomePhone = ();
    string?  OtherPhone = ();
    string?  AssistantPhone = ();
    string?  ReportsToId = ();
    string?  Email = ();
    string?  Title = ();
    string?  Department = ();
    string?  AssistantName = ();
    anydata?  LeadSource = ();
    string?  Birthdate = ();
    string?  Description = ();
    string  OwnerId?;
    string  CreatedDate?;
    string  CreatedById?;
    string  LastModifiedDate?;
    string  LastModifiedById?;
    string  SystemModstamp?;
    string?  LastActivityDate?;
    string?  LastCURequestDate?;
    string?  LastCUUpdateDate?;
    string?  LastViewedDate?;
    string?  LastReferencedDate?;
    string?  EmailBouncedReason = ();
    string?  EmailBouncedDate = ();
    boolean  IsEmailBounced?;
    string?  PhotoUrl?;
    string?  Jigsaw = ();
    string?  JigsawContactId?;
    anydata?  CleanStatus = ();
    string?  IndividualId = ();
    anydata?  Level__c = ();
    string?  Languages__c = ();
    string?  My_External_Id__c = ();
};
