public type Opportunity record {
    string  Id?;
    boolean  IsDeleted?;
    string?  AccountId = ();
    boolean  IsPrivate?;
    string  Name?;
    string?  Description = ();
    anydata  StageName?;
    float?  Amount = ();
    float?  Probability = ();
    float?  ExpectedRevenue?;
    float?  TotalOpportunityQuantity = ();
    string  CloseDate?;
    anydata?  Type = ();
    string?  NextStep = ();
    anydata?  LeadSource = ();
    boolean  IsClosed?;
    boolean  IsWon?;
    anydata  ForecastCategory?;
    anydata?  ForecastCategoryName = ();
    string?  CampaignId = ();
    boolean  HasOpportunityLineItem?;
    string?  Pricebook2Id = ();
    string  OwnerId?;
    string  CreatedDate?;
    string  CreatedById?;
    string  LastModifiedDate?;
    string  LastModifiedById?;
    string  SystemModstamp?;
    string?  LastActivityDate?;
    int?  FiscalQuarter?;
    int?  FiscalYear?;
    string?  Fiscal?;
    string?  ContactId = ();
    string?  LastViewedDate?;
    string?  LastReferencedDate?;
    boolean  HasOpenActivity?;
    boolean  HasOverdueTask?;
    anydata?  DeliveryInstallationStatus__c = ();
    string?  TrackingNumber__c = ();
    string?  OrderNumber__c = ();
    string?  CurrentGenerators__c = ();
    string?  MainCompetitors__c = ();
};
