// This is an autogenerated file. Do not edit. Run 'npm run gen-models' to generate.
// Run 'BALLERINA_HOME="your/ballerina/home" npm run gen-ast-interfaces' to generate.
// tslint:disable:ban-types
export interface ASTNode {
  id: string;
  kind: string;
  viewState?: any;
  ws?: any[];
}

export interface Abort extends ASTNode {
  position: any;
  ws: any[];
}

export interface Annotation extends ASTNode {
  abstract: boolean;
  annotationAttachments: any;
  attached: boolean;
  attachmentPoints: string[];
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultable_checked: boolean;
  deprecated: boolean;
  deprecatedAttachments: any;
  final: boolean;
  function_final: boolean;
  interface: boolean;
  lambda: boolean;
  markdownDocumentationAttachment?: MarkdownDocumentation;
  name: Identifier;
  native: boolean;
  noAttachmentPoints?: boolean;
  optional: boolean;
  parallel: boolean;
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  testable: boolean;
  typeNode: UserDefinedType;
  ws: any[];
}

export interface AnnotationAttachment extends ASTNode {
  annotationName: Identifier;
  expression?: RecordLiteralExpr;
  packageAlias: Identifier;
  position: any;
  ws: any[];
}

export interface ArrayLiteralExpr extends ASTNode {
  expressions: Array<
    | Literal
    | SimpleVariableRef
    | Invocation
    | TypeConversionExpr
    | BracedTupleExpr
    | RecordLiteralExpr
    | ArrayLiteralExpr
    | IndexBasedAccessExpr
    | FieldBasedAccessExpr
    | TypeInitExpr
    | UnaryExpr
  >;
  isExpression?: boolean;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface ArrayType extends ASTNode {
  dimensionAsString?: string;
  dimensions: number;
  elementType:
    | ValueType
    | UserDefinedType
    | ArrayType
    | BuiltInRefType
    | FunctionType
    | UnionTypeNode
    | TupleTypeNode
    | ConstrainedType;
  grouped: boolean;
  isRestParam?: boolean;
  nullable: boolean;
  nullableOperatorAvailable?: boolean;
  position?: any;
  sizes: number[];
  symbolType: string[];
  ws?: any[];
}

export interface ArrowExpr extends ASTNode {
  expression:
    | BinaryExpr
    | UnaryExpr
    | BracedTupleExpr
    | SimpleVariableRef
    | MatchExpression
    | ArrowExpr
    | Lambda
    | StringTemplateLiteral
    | Invocation
    | IndexBasedAccessExpr
    | TypeConversionExpr
    | Literal;
  hasParantheses?: boolean;
  isExpression?: boolean;
  parameters: Variable[];
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface Assignment extends ASTNode {
  declaredWithVar: boolean;
  expression:
    | SimpleVariableRef
    | IndexBasedAccessExpr
    | Literal
    | ArrayLiteralExpr
    | AwaitExpr
    | Invocation
    | CheckExpr
    | TypeConversionExpr
    | MatchExpression
    | Lambda
    | BinaryExpr
    | RecordLiteralExpr
    | UnaryExpr
    | TypeInitExpr
    | FieldBasedAccessExpr
    | TernaryExpr
    | XmlElementLiteral
    | ElvisExpr
    | ArrowExpr
    | BracedTupleExpr
    | StringTemplateLiteral
    | TypedescExpression
    | XmlCommentLiteral
    | XmlPiLiteral
    | XmlTextLiteral;
  position: any;
  variable:
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr
    | SimpleVariableRef
    | XmlAttributeAccessExpr;
  ws: any[];
}

export interface AwaitExpr extends ASTNode {
  expression: SimpleVariableRef;
  isExpression?: boolean;
  position: any;
  symbolType: string[];
  ws: any[];
}

export interface BinaryExpr extends ASTNode {
  inTemplateLiteral?: boolean;
  isExpression?: boolean;
  leftExpression:
    | BinaryExpr
    | SimpleVariableRef
    | FieldBasedAccessExpr
    | Literal
    | Invocation
    | IndexBasedAccessExpr
    | UnaryExpr
    | BracedTupleExpr
    | TypeConversionExpr
    | CheckExpr
    | StringTemplateLiteral;
  operatorKind: string;
  position: any;
  rightExpression:
    | SimpleVariableRef
    | Literal
    | Invocation
    | CheckExpr
    | FieldBasedAccessExpr
    | BinaryExpr
    | UnaryExpr
    | IndexBasedAccessExpr
    | BracedTupleExpr
    | TypeConversionExpr
    | AwaitExpr
    | StringTemplateLiteral
    | XmlElementLiteral;
  symbolType?: string[];
  ws?: any[];
}

export interface Block extends ASTNode {
  isElseBlock?: boolean;
  position?: any;
  statements: Array<
    | VariableDef
    | WorkerReceive
    | Assignment
    | WorkerSend
    | Return
    | ExpressionStatement
    | ForkJoin
    | While
    | If
    | TupleDestructure
    | Match
    | Xmlns
    | CompoundAssignment
    | Foreach
    | Try
    | Break
    | Transaction
    | Throw
    | Forever
    | Abort
    | Next
    | Done
    | Retry
    | Scope
    | Compensate
    | Lock
  >;
  ws?: any[];
}

export interface BracedTupleExpr extends ASTNode {
  expressions: Array<
    | BinaryExpr
    | SimpleVariableRef
    | Invocation
    | FieldBasedAccessExpr
    | UnaryExpr
    | XmlAttributeAccessExpr
    | Literal
    | IndexBasedAccessExpr
    | ArrayLiteralExpr
    | TypedescExpression
    | MatchExpression
    | BracedTupleExpr
    | ElvisExpr
    | TypeConversionExpr
    | TypeInitExpr
    | TernaryExpr
    | RecordLiteralExpr
    | CheckExpr
  >;
  isExpression?: boolean;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface Break extends ASTNode {
  position: any;
  ws: any[];
}

export interface BuiltInRefType extends ASTNode {
  grouped: boolean;
  nullable: boolean;
  nullableOperatorAvailable?: boolean;
  position: any;
  symbolType: string[];
  typeKind: string;
  ws: any[];
}

export interface Catch extends ASTNode {
  body: Block;
  parameter: Variable;
  position: any;
  ws: any[];
}

export interface CheckExpr extends ASTNode {
  expression:
    | TypeConversionExpr
    | Invocation
    | FieldBasedAccessExpr
    | SimpleVariableRef;
  isExpression?: boolean;
  operatorKind: string;
  position: any;
  symbolType: string[];
  ws: any[];
}

export interface Compensate extends ASTNode {
  position: any;
  scopeName: Identifier;
  ws: any[];
}

export interface CompilationUnit extends ASTNode {
  name: string;
  position: any;
  topLevelNodes: Array<
    | Function
    | Import
    | TypeDefinition
    | Variable
    | Xmlns
    | Service
    | Endpoint
    | Annotation
  >;
  ws: any[];
}

export interface CompoundAssignment extends ASTNode {
  compoundOperator: string;
  expression:
    | Literal
    | SimpleVariableRef
    | BinaryExpr
    | FieldBasedAccessExpr
    | BracedTupleExpr
    | Invocation
    | TypeConversionExpr
    | IndexBasedAccessExpr;
  operatorKind: string;
  position: any;
  variable:
    | SimpleVariableRef
    | IndexBasedAccessExpr
    | FieldBasedAccessExpr
    | XmlAttributeAccessExpr
    | Invocation;
  ws: any[];
}

export interface ConstrainedType extends ASTNode {
  constraint:
    | ValueType
    | UnionTypeNode
    | BuiltInRefType
    | UserDefinedType
    | TupleTypeNode
    | ArrayType
    | ConstrainedType;
  grouped: boolean;
  nullable: boolean;
  nullableOperatorAvailable?: boolean;
  position: any;
  symbolType: string[];
  type: BuiltInRefType;
  ws: any[];
}

export interface Deprecated extends ASTNode {
  deprecatedStart: string;
  documentationText: string;
  position: any;
  ws: any[];
}

export interface DocumentationDescription extends ASTNode {
  position: any;
  text: string;
  ws?: any[];
}

export interface DocumentationParameter extends ASTNode {
  parameterDocumentation?: string;
  parameterDocumentationLines?: string[];
  parameterName?: Identifier;
  position: any;
  returnParameterDocumentation?: string;
  returnParameterDocumentationLines?: string[];
  ws: any[];
}

export interface Done extends ASTNode {
  position: any;
  ws: any[];
}

export interface ElvisExpr extends ASTNode {
  isExpression?: boolean;
  leftExpression:
    | SimpleVariableRef
    | Invocation
    | IndexBasedAccessExpr
    | FieldBasedAccessExpr
    | ElvisExpr;
  position: any;
  rightExpression: Literal | SimpleVariableRef | BracedTupleExpr;
  symbolType: string[];
  ws: any[];
}

export interface Endpoint extends ASTNode {
  abstract: boolean;
  annotationAttachments: AnnotationAttachment[];
  attached: boolean;
  compensate: boolean;
  configurationExpression?: RecordLiteralExpr | Invocation | SimpleVariableRef;
  connector: boolean;
  defaultable: boolean;
  defaultable_checked: boolean;
  deprecated: boolean;
  endPointType: UserDefinedType;
  final: boolean;
  function_final: boolean;
  interface: boolean;
  isConfigAssignment?: boolean;
  lambda: boolean;
  name: Identifier;
  native: boolean;
  optional: boolean;
  parallel: boolean;
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  symbolType: string[];
  testable: boolean;
  ws: any[];
}

export interface ExpressionStatement extends ASTNode {
  expression:
    | Invocation
    | MatchExpression
    | CheckExpr
    | AwaitExpr
    | SimpleVariableRef
    | XmlTextLiteral
    | ArrayLiteralExpr
    | RecordLiteralExpr
    | TypedescExpression;
  position: any;
  ws: any[];
}

export interface FieldBasedAccessExpr extends ASTNode {
  errorLifting?: boolean;
  expression:
    | SimpleVariableRef
    | Invocation
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr;
  fieldName: Identifier;
  isExpression?: boolean;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface FiniteTypeNode extends ASTNode {
  grouped: boolean;
  nullable: boolean;
  symbolType: string[];
  valueSet: Literal[];
  ws?: any[];
}

export interface Foreach extends ASTNode {
  body: Block;
  collection:
    | SimpleVariableRef
    | Invocation
    | BinaryExpr
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr;
  position: any;
  variables: Array<SimpleVariableRef | FieldBasedAccessExpr>;
  withParantheses?: boolean;
  ws: any[];
}

export interface Forever extends ASTNode {
  position: any;
  siddhiRuntimeEnabled: boolean;
  streamingQueryStatements: StreamingQuery[];
  ws: any[];
}

export interface ForkJoin extends ASTNode {
  joinBody: Block;
  joinCount: number;
  joinResultVar: Variable;
  joinType: string;
  joinedWorkerIdentifiers: Identifier[];
  position: any;
  timeOutExpression?: Literal;
  timeOutVariable?: Variable;
  timeoutBody?: Block;
  workers: Worker[];
  ws: any[];
}

export interface Function extends ASTNode {
  abstract: boolean;
  allParams: Array<Variable | VariableDef>;
  annotationAttachments: AnnotationAttachment[];
  attached: boolean;
  body?: Block;
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultableParameters: VariableDef[];
  defaultable_checked: boolean;
  deprecated: boolean;
  deprecatedAttachments: Deprecated[];
  endpointNodes: Endpoint[];
  final: boolean;
  function_final: boolean;
  hasRestParams?: boolean;
  hasReturns?: boolean;
  interface: boolean;
  isConstructor?: boolean;
  isStreamAction?: boolean;
  lambda: boolean;
  markdownDocumentationAttachment?: MarkdownDocumentation;
  name: Identifier;
  native: boolean;
  noVisibleReceiver?: boolean;
  objectOuterFunction?: boolean;
  objectOuterFunctionTypeName?: Identifier;
  optional: boolean;
  parallel: boolean;
  parameters: Array<Variable | VariableDef>;
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  receiver?: Variable;
  record: boolean;
  restParameters?: Variable;
  returnTypeAnnotationAttachments: AnnotationAttachment[];
  returnTypeNode:
    | ValueType
    | TupleTypeNode
    | UnionTypeNode
    | FunctionType
    | ArrayType
    | ConstrainedType
    | UserDefinedType
    | BuiltInRefType;
  testable: boolean;
  workers: Worker[];
  ws?: any[];
}

export interface FunctionType extends ASTNode {
  grouped: boolean;
  hasReturn?: boolean;
  nullable: boolean;
  params: Variable[];
  position: any;
  returnKeywordExists: boolean;
  returnTypeNode:
    | ValueType
    | FunctionType
    | UserDefinedType
    | ArrayType
    | TupleTypeNode
    | UnionTypeNode;
  symbolType: string[];
  withParantheses?: boolean;
  ws: any[];
}

export interface GroupBy extends ASTNode {
  position: any;
  variables: Array<FieldBasedAccessExpr | SimpleVariableRef>;
  ws: any[];
}

export interface Having extends ASTNode {
  expression: BinaryExpr;
  position: any;
  ws: any[];
}

export interface Identifier extends ASTNode {
  literal: boolean;
  position?: any;
  value: string;
  valueWithBar: string;
}

export interface If extends ASTNode {
  body: Block;
  condition:
    | BracedTupleExpr
    | BinaryExpr
    | UnaryExpr
    | SimpleVariableRef
    | Literal;
  elseStatement?: Block | If;
  isElseIfBlock?: boolean;
  ladderParent?: boolean;
  position: any;
  ws: any[];
}

export interface Import extends ASTNode {
  alias: Identifier;
  isInternal?: boolean;
  orgName: Identifier;
  packageName: Identifier[];
  packageVersion: Identifier;
  position: any;
  userDefinedAlias?: boolean;
  ws?: any[];
}

export interface IndexBasedAccessExpr extends ASTNode {
  expression:
    | SimpleVariableRef
    | IndexBasedAccessExpr
    | FieldBasedAccessExpr
    | Invocation;
  index:
    | SimpleVariableRef
    | Literal
    | TypeConversionExpr
    | BinaryExpr
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr
    | UnaryExpr
    | Invocation;
  isExpression?: boolean;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface IntRangeExpr extends ASTNode {
  endExpression?: Literal;
  isWrappedWithBracket: boolean;
  position: any;
  startExpression: Literal;
  ws: any[];
}

export interface Invocation extends ASTNode {
  actionInvocation: boolean;
  argumentExpressions: Array<
    | SimpleVariableRef
    | Literal
    | RecordLiteralExpr
    | XmlAttributeAccessExpr
    | Lambda
    | FieldBasedAccessExpr
    | TypeConversionExpr
    | UnaryExpr
    | BinaryExpr
    | Invocation
    | IndexBasedAccessExpr
    | RestArgsExpr
    | NamedArgsExpr
    | ArrayLiteralExpr
    | StringTemplateLiteral
    | TypeInitExpr
    | MatchExpression
    | TernaryExpr
    | ArrowExpr
    | CheckExpr
    | BracedTupleExpr
    | XmlElementLiteral
  >;
  async: boolean;
  expression?:
    | SimpleVariableRef
    | Invocation
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr;
  invocationType?: string;
  isExpression?: boolean;
  iterableOperation: boolean;
  name: Identifier;
  packageAlias: Identifier;
  position: any;
  symbolType: any;
  ws: any[];
}

export interface JoinStreamingInput extends ASTNode {
  joinType: string;
  onExpression?: BinaryExpr;
  position: any;
  streamingInput: StreamingInput;
  unidirectionalAfterJoin: boolean;
  unidirectionalBeforeJoin: boolean;
  ws: any[];
}

export interface Lambda extends ASTNode {
  functionNode: Function;
  isExpression?: boolean;
  position: any;
  symbolType?: string[];
}

export interface Limit extends ASTNode {
  limitValue: string;
  position: any;
  ws: any[];
}

export interface Literal extends ASTNode {
  emptyParantheses?: boolean;
  endTemplateLiteral?: boolean;
  inTemplateLiteral?: boolean;
  isExpression?: boolean;
  lastNodeValue?: boolean;
  originalValue?: string;
  position: any;
  startTemplateLiteral?: boolean;
  symbolType?: string[];
  unescapedValue?: string;
  value: string;
  ws?: any[];
}

export interface Lock extends ASTNode {
  body: Block;
  position: any;
  ws: any[];
}

export interface MarkdownDocumentation extends ASTNode {
  documentation: string;
  documentationLines: DocumentationDescription[];
  parameterDocumentations: string;
  parameters: DocumentationParameter[];
  position: any;
  returnParameter?: DocumentationParameter;
  returnParameterDocumentation?: string;
  ws: any[];
}

export interface Match extends ASTNode {
  expression:
    | SimpleVariableRef
    | BracedTupleExpr
    | Invocation
    | FieldBasedAccessExpr
    | TypeConversionExpr
    | IndexBasedAccessExpr;
  patternClauses: MatchPatternClause[];
  position: any;
  ws: any[];
}

export interface MatchExpression extends ASTNode {
  expression:
    | Invocation
    | SimpleVariableRef
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr
    | BracedTupleExpr;
  isExpression?: boolean;
  patternClauses: MatchExpressionPatternClause[];
  position: any;
  symbolType: string[];
  ws: any[];
}

export interface MatchExpressionPatternClause extends ASTNode {
  position: any;
  statement:
    | Invocation
    | SimpleVariableRef
    | Literal
    | BinaryExpr
    | FieldBasedAccessExpr
    | BracedTupleExpr
    | MatchExpression
    | RecordLiteralExpr
    | TypeConversionExpr;
  variableNode: Variable;
  ws: any[];
}

export interface MatchPatternClause extends ASTNode {
  position: any;
  statement: Block;
  variableNode: Variable;
  withCurlies?: boolean;
  ws: any[];
}

export interface NamedArgsExpr extends ASTNode {
  expression:
    | SimpleVariableRef
    | Literal
    | RecordLiteralExpr
    | UnaryExpr
    | FieldBasedAccessExpr
    | IndexBasedAccessExpr;
  name: Identifier;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface Next extends ASTNode {
  position: any;
  ws: any[];
}

export interface ObjectType extends ASTNode {
  fields: Variable[];
  functions: Function[];
  grouped: boolean;
  initFunction?: Function;
  nullable: boolean;
  position: any;
  symbolType: string[];
  typeReferences: Array<UserDefinedType | ConstrainedType | ValueType>;
}

export interface OrderBy extends ASTNode {
  position: any;
  variables: OrderByVariable[];
  ws: any[];
}

export interface OrderByVariable extends ASTNode {
  noVisibleType?: boolean;
  orderByType: string;
  position: any;
  typeString?: string;
  variableReference: SimpleVariableRef | Invocation;
  ws?: any[];
}

export interface OutputRateLimit extends ASTNode {
  outputRateType: string;
  position: any;
  rateLimitValue: string;
  snapshot: boolean;
  timeScale?: string;
  ws: any[];
}

export interface PatternClause extends ASTNode {
  forAllEvents: boolean;
  patternStreamingNode: PatternStreamingInput;
  position: any;
  withinClause?: Within;
  ws: any[];
}

export interface PatternStreamingEdgeInput extends ASTNode {
  aliasIdentifier?: string;
  expression?: IntRangeExpr;
  position: any;
  streamReference: SimpleVariableRef;
  whereClause?: Where;
  ws?: any[];
}

export interface PatternStreamingInput extends ASTNode {
  andOnly: boolean;
  andWithNot: boolean;
  commaSeparated: boolean;
  followedBy: boolean;
  forWithNot: boolean;
  orOnly: boolean;
  patternStreamingEdgeInputs: PatternStreamingEdgeInput[];
  patternStreamingInput?: PatternStreamingInput;
  position: any;
  timeDurationValue?: string;
  timeScale?: string;
  ws?: any[];
}

export interface RecordLiteralExpr extends ASTNode {
  isExpression?: boolean;
  keyValuePairs: RecordLiteralKeyValue[];
  position?: any;
  symbolType?: string[];
  ws: any[];
}

export interface RecordLiteralKeyValue extends ASTNode {
  key:
    | SimpleVariableRef
    | Literal
    | BracedTupleExpr
    | Invocation
    | IndexBasedAccessExpr
    | StringTemplateLiteral;
  value:
    | Literal
    | ArrayLiteralExpr
    | RecordLiteralExpr
    | Invocation
    | BinaryExpr
    | SimpleVariableRef
    | UnaryExpr
    | FieldBasedAccessExpr
    | TypedescExpression
    | IndexBasedAccessExpr
    | BracedTupleExpr
    | Lambda
    | TernaryExpr
    | TypeInitExpr;
  ws?: any[];
}

export interface RecordType extends ASTNode {
  fields: Variable[];
  grouped: boolean;
  isRestFieldAvailable?: boolean;
  nullable: boolean;
  position: any;
  restFieldType?:
    | ValueType
    | BuiltInRefType
    | UnionTypeNode
    | UserDefinedType
    | TupleTypeNode;
  sealed: boolean;
  symbolType: string[];
  typeReferences: any;
  ws?: any[];
}

export interface Resource extends ASTNode {
  abstract: boolean;
  annotationAttachments: AnnotationAttachment[];
  attached: boolean;
  body: Block;
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultableParameters: any;
  defaultable_checked: boolean;
  deprecated: boolean;
  deprecatedAttachments: any;
  endpointNodes: Endpoint[];
  final: boolean;
  function_final: boolean;
  interface: boolean;
  lambda: boolean;
  markdownDocumentationAttachment?: MarkdownDocumentation;
  name: Identifier;
  native: boolean;
  optional: boolean;
  parallel: boolean;
  parameters: Variable[];
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  returnTypeAnnotationAttachments: any;
  returnTypeNode: ValueType;
  testable: boolean;
  workers: Worker[];
  ws: any[];
}

export interface RestArgsExpr extends ASTNode {
  expression: SimpleVariableRef | Invocation;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface Retry extends ASTNode {
  position: any;
  ws: any[];
}

export interface Return extends ASTNode {
  expression:
    | BinaryExpr
    | SimpleVariableRef
    | Literal
    | Lambda
    | Invocation
    | FieldBasedAccessExpr
    | BracedTupleExpr
    | IndexBasedAccessExpr
    | ArrayLiteralExpr
    | RecordLiteralExpr
    | CheckExpr
    | XmlElementLiteral
    | TypeConversionExpr
    | TypeInitExpr
    | ElvisExpr
    | TernaryExpr
    | AwaitExpr
    | MatchExpression
    | ArrowExpr
    | UnaryExpr
    | XmlAttributeAccessExpr;
  noExpressionAvailable?: boolean;
  position: any;
  ws: any[];
}

export interface Scope extends ASTNode {
  position: any;
  scopeBody: Block;
  scopeName: Identifier;
  ws: any[];
}

export interface SelectClause extends ASTNode {
  groupBy?: GroupBy;
  having?: Having;
  notVisible?: boolean;
  position?: any;
  selectAll: boolean;
  selectExpressions?: SelectExpression[];
  ws?: any[];
}

export interface SelectExpression extends ASTNode {
  expression:
    | SimpleVariableRef
    | Invocation
    | FieldBasedAccessExpr
    | TernaryExpr
    | Literal
    | BracedTupleExpr
    | BinaryExpr;
  identifier?: string;
  identifierAvailable?: boolean;
  position: any;
  ws?: any[];
}

export interface Service extends ASTNode {
  annotationAttachments: AnnotationAttachment[];
  anonymousEndpointBind?: RecordLiteralExpr;
  bindNotAvailable?: boolean;
  boundEndpoints: SimpleVariableRef[];
  deprecatedAttachments: any;
  endpointNodes: any;
  initFunction: Function;
  isServiceTypeUnavailable?: boolean;
  markdownDocumentationAttachment?: MarkdownDocumentation;
  name: Identifier;
  namespaceDeclarations: Xmlns[];
  position: any;
  resources: Resource[];
  serviceTypeStruct?: UserDefinedType;
  variables: VariableDef[];
  ws: any[];
}

export interface SimpleVariableRef extends ASTNode {
  inTemplateLiteral?: boolean;
  isExpression?: boolean;
  packageAlias?: Identifier;
  position: any;
  symbolType?: string[];
  variableName: Identifier;
  ws?: any[];
}

export interface StreamAction extends ASTNode {
  invokableBody: Lambda;
  position: any;
  ws: any[];
}

export interface StreamingInput extends ASTNode {
  afterStreamingCondition?: Where;
  alias?: string;
  aliasAvailable?: boolean;
  beforeStreamingCondition?: Where;
  position: any;
  postFunctionInvocations?: Invocation[];
  streamReference: SimpleVariableRef;
  windowClause?: WindowClause;
  windowTraversedAfterWhere: boolean;
  ws?: any[];
}

export interface StreamingQuery extends ASTNode {
  joiningInput?: JoinStreamingInput;
  orderbyClause?: OrderBy;
  outputRateLimitNode?: OutputRateLimit;
  patternClause?: PatternClause;
  position: any;
  selectClause: SelectClause;
  streamingAction: StreamAction;
  streamingInput?: StreamingInput;
  ws: any[];
}

export interface StringTemplateLiteral extends ASTNode {
  expressions: Array<
    | Literal
    | SimpleVariableRef
    | BinaryExpr
    | Invocation
    | TernaryExpr
    | FieldBasedAccessExpr
    | UnaryExpr
  >;
  isExpression?: boolean;
  position: any;
  startTemplate: string;
  symbolType: string[];
  ws: any[];
}

export interface Table extends ASTNode {
  dataRows: Array<RecordLiteralExpr | SimpleVariableRef | Literal>;
  isExpression: boolean;
  position: any;
  symbolType: string[];
  tableColumns: TableColumn[];
  ws: any[];
}

export interface TableColumn extends ASTNode {
  flagSet: string[];
  name: string;
  position: any;
  ws: any[];
}

export interface TableQuery extends ASTNode {
  joinStreamingInput?: JoinStreamingInput;
  limitClause?: Limit;
  orderByNode?: OrderBy;
  position: any;
  selectClauseNode: SelectClause;
  streamingInput: StreamingInput;
  ws: any[];
}

export interface TableQueryExpression extends ASTNode {
  isExpression: boolean;
  position: any;
  symbolType: string[];
  tableQuery: TableQuery;
}

export interface TernaryExpr extends ASTNode {
  condition: BinaryExpr | BracedTupleExpr | SimpleVariableRef | Literal;
  elseExpression:
    | Literal
    | BinaryExpr
    | SimpleVariableRef
    | TernaryExpr
    | Invocation
    | BracedTupleExpr
    | IndexBasedAccessExpr;
  isExpression?: boolean;
  position: any;
  symbolType?: string[];
  thenExpression:
    | Literal
    | BinaryExpr
    | SimpleVariableRef
    | Invocation
    | TernaryExpr
    | BracedTupleExpr
    | IndexBasedAccessExpr;
  ws: any[];
}

export interface Throw extends ASTNode {
  expressions: SimpleVariableRef | MatchExpression | Invocation;
  position: any;
  ws: any[];
}

export interface Transaction extends ASTNode {
  onAbortFunction?: SimpleVariableRef;
  onCommitFunction?: SimpleVariableRef;
  onRetryBody?: Block;
  position: any;
  retryCount?: Literal | SimpleVariableRef;
  transactionBody: Block;
  ws: any[];
}

export interface Try extends ASTNode {
  body: Block;
  catchBlocks: Catch[];
  finallyBody?: Block;
  position: any;
  ws: any[];
}

export interface TupleDestructure extends ASTNode {
  declaredWithVar: boolean;
  expression: Invocation | CheckExpr | SimpleVariableRef | BracedTupleExpr;
  position: any;
  variableRefs: SimpleVariableRef[];
  ws: any[];
}

export interface TupleTypeNode extends ASTNode {
  grouped: boolean;
  memberTypeNodes: Array<
    | ValueType
    | BuiltInRefType
    | UserDefinedType
    | UnionTypeNode
    | TupleTypeNode
    | ArrayType
    | ConstrainedType
  >;
  nullable: boolean;
  nullableOperatorAvailable?: boolean;
  position: any;
  symbolType: string[];
  ws: any[];
}

export interface TypeConversionExpr extends ASTNode {
  expression:
    | SimpleVariableRef
    | IndexBasedAccessExpr
    | Invocation
    | FieldBasedAccessExpr
    | XmlAttributeAccessExpr
    | BracedTupleExpr
    | TypeConversionExpr
    | Literal;
  isExpression?: boolean;
  position: any;
  symbolType: string[];
  typeNode:
    | ValueType
    | BuiltInRefType
    | ArrayType
    | TupleTypeNode
    | UserDefinedType
    | ConstrainedType
    | FunctionType;
  ws: any[];
}

export interface TypeDefinition extends ASTNode {
  abstract: boolean;
  annotationAttachments: any;
  attached: boolean;
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultable_checked: boolean;
  deprecated: boolean;
  deprecatedAttachments: any;
  final: boolean;
  function_final: boolean;
  interface: boolean;
  isAbstractKeywordAvailable?: boolean;
  isObjectType?: boolean;
  isRecordKeywordAvailable?: boolean;
  isRecordType?: boolean;
  lambda: boolean;
  markdownDocumentationAttachment?: MarkdownDocumentation;
  name: Identifier;
  native: boolean;
  notVisible?: boolean;
  optional: boolean;
  parallel: boolean;
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  testable: boolean;
  typeNode:
    | ObjectType
    | RecordType
    | UnionTypeNode
    | FiniteTypeNode
    | UserDefinedType
    | ValueType
    | ArrayType
    | ConstrainedType;
  ws?: any[];
}

export interface TypeInitExpr extends ASTNode {
  expressions: Array<
    | Literal
    | SimpleVariableRef
    | NamedArgsExpr
    | IndexBasedAccessExpr
    | TypeInitExpr
    | FieldBasedAccessExpr
    | Lambda
    | RecordLiteralExpr
    | ArrayLiteralExpr
    | BinaryExpr
    | Invocation
  >;
  hasParantheses?: boolean;
  isExpression?: boolean;
  noExpressionAvailable?: boolean;
  noTypeAttached?: boolean;
  position: any;
  symbolType?: string[];
  type?: UserDefinedType;
  typeName?: Identifier;
  ws: any[];
}

export interface TypedescExpression extends ASTNode {
  isExpression?: boolean;
  isObject?: boolean;
  isRecord?: boolean;
  position: any;
  symbolType: string[];
  typeNode:
    | ValueType
    | BuiltInRefType
    | ConstrainedType
    | UserDefinedType
    | ArrayType
    | UnionTypeNode;
  ws?: any[];
}

export interface UnaryExpr extends ASTNode {
  expression:
    | SimpleVariableRef
    | IndexBasedAccessExpr
    | Invocation
    | FieldBasedAccessExpr
    | CheckExpr
    | BracedTupleExpr
    | Literal
    | StringTemplateLiteral
    | UnaryExpr
    | TypeInitExpr;
  inTemplateLiteral?: boolean;
  isExpression?: boolean;
  operatorKind: string;
  position: any;
  symbolType?: string[];
  ws: any[];
}

export interface UnionTypeNode extends ASTNode {
  grouped: boolean;
  memberTypeNodes: Array<
    | ValueType
    | UserDefinedType
    | BuiltInRefType
    | TupleTypeNode
    | ArrayType
    | FunctionType
    | ConstrainedType
  >;
  nullable: boolean;
  position?: any;
  symbolType: string[];
  withParantheses?: boolean;
  ws?: any[];
}

export interface UserDefinedType extends ASTNode {
  abstract: boolean;
  anonType?: ObjectType | RecordType | FiniteTypeNode;
  attached: boolean;
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultable_checked: boolean;
  deprecated: boolean;
  final: boolean;
  function_final: boolean;
  grouped: boolean;
  interface: boolean;
  isAnonType?: boolean;
  lambda: boolean;
  native: boolean;
  nullable: boolean;
  nullableOperatorAvailable?: boolean;
  optional: boolean;
  packageAlias: Identifier;
  parallel: boolean;
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  symbolType: string[];
  testable: boolean;
  typeName: Identifier;
  ws?: any[];
}

export interface ValueType extends ASTNode {
  emptyParantheses?: boolean;
  grouped: boolean;
  nullable: boolean;
  nullableOperatorAvailable?: boolean;
  position?: any;
  symbolType?: string[];
  typeKind: string;
  withParantheses?: boolean;
  ws?: any[];
}

export interface Variable extends ASTNode {
  abstract: boolean;
  annotationAttachments: AnnotationAttachment[];
  arrowExprParam?: boolean;
  attached: boolean;
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultable_checked: boolean;
  deprecated: boolean;
  deprecatedAttachments: any;
  endWithSemicolon?: boolean;
  final: boolean;
  function_final: boolean;
  global?: boolean;
  inObject?: boolean;
  initialExpression?:
    | TypeInitExpr
    | Lambda
    | ArrowExpr
    | ArrayLiteralExpr
    | Literal
    | CheckExpr
    | SimpleVariableRef
    | Invocation
    | AwaitExpr
    | RecordLiteralExpr
    | XmlElementLiteral
    | Table
    | FieldBasedAccessExpr
    | TypeConversionExpr
    | BinaryExpr
    | MatchExpression
    | ElvisExpr
    | IndexBasedAccessExpr
    | StringTemplateLiteral
    | UnaryExpr
    | TableQueryExpression
    | BracedTupleExpr
    | XmlAttributeAccessExpr
    | XmlTextLiteral
    | XmlCommentLiteral
    | XmlPiLiteral
    | TernaryExpr
    | TypedescExpression;
  interface: boolean;
  isAnonType?: boolean;
  lambda: boolean;
  markdownDocumentationAttachment?: MarkdownDocumentation;
  name: Identifier;
  native: boolean;
  noVisibleName?: boolean;
  optional: boolean;
  parallel: boolean;
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  rest?: boolean;
  safeAssignment: boolean;
  serviceEndpoint?: boolean;
  symbolType?: string[];
  testable: boolean;
  typeNode?:
    | ValueType
    | UserDefinedType
    | FunctionType
    | ArrayType
    | ConstrainedType
    | BuiltInRefType
    | TupleTypeNode
    | UnionTypeNode;
  ws?: any[];
}

export interface VariableDef extends ASTNode {
  defaultable?: boolean;
  position: any;
  variable: Variable;
  ws: any[];
}

export interface Where extends ASTNode {
  expression: BinaryExpr;
  position: any;
  ws: any[];
}

export interface While extends ASTNode {
  body: Block;
  condition: BracedTupleExpr | BinaryExpr | Literal;
  position: any;
  ws: any[];
}

export interface WindowClause extends ASTNode {
  functionInvocation: Invocation;
  position: any;
  ws: any[];
}

export interface Within extends ASTNode {
  position: any;
  timeDurationValue: string;
  timeScale: string;
  ws: any[];
}

export interface Worker extends ASTNode {
  abstract: boolean;
  annotationAttachments: any;
  attached: boolean;
  body: Block;
  compensate: boolean;
  connector: boolean;
  defaultable: boolean;
  defaultableParameters: any;
  defaultable_checked: boolean;
  deprecated: boolean;
  deprecatedAttachments: any;
  endpointNodes: any;
  final: boolean;
  function_final: boolean;
  interface: boolean;
  lambda: boolean;
  name: Identifier;
  native: boolean;
  optional: boolean;
  parallel: boolean;
  parameters: Variable[];
  position: any;
  private: boolean;
  public: boolean;
  readonly: boolean;
  record: boolean;
  returnTypeAnnotationAttachments: any;
  returnTypeNode?:
    | ValueType
    | BuiltInRefType
    | TupleTypeNode
    | ArrayType
    | UserDefinedType;
  testable: boolean;
  workers: any;
  ws: any[];
}

export interface WorkerReceive extends ASTNode {
  expression: SimpleVariableRef | BracedTupleExpr | IndexBasedAccessExpr;
  keyExpression?: SimpleVariableRef;
  position: any;
  workerName: Identifier;
  ws: any[];
}

export interface WorkerSend extends ASTNode {
  expression:
    | SimpleVariableRef
    | BracedTupleExpr
    | Literal
    | IndexBasedAccessExpr
    | BinaryExpr;
  forkJoinedSend: boolean;
  keyExpression?: SimpleVariableRef;
  position: any;
  workerName: Identifier;
  ws: any[];
}

export interface XmlAttribute extends ASTNode {
  inTemplateLiteral: boolean;
  name: XmlQname | SimpleVariableRef | BinaryExpr;
  position: any;
  symbolType: string[];
  value: XmlQuotedString;
  ws: any[];
}

export interface XmlAttributeAccessExpr extends ASTNode {
  expression: FieldBasedAccessExpr | IndexBasedAccessExpr | SimpleVariableRef;
  index?: Literal | SimpleVariableRef;
  isExpression?: boolean;
  position: any;
  symbolType: string[];
  ws: any[];
}

export interface XmlCommentLiteral extends ASTNode {
  inTemplateLiteral?: boolean;
  isExpression?: boolean;
  position: any;
  root?: boolean;
  startLiteral?: string;
  symbolType: string[];
  textFragments: Array<Literal | SimpleVariableRef | BinaryExpr>;
  ws: any[];
}

export interface XmlElementLiteral extends ASTNode {
  attributes: XmlAttribute[];
  content: Array<
    | XmlElementLiteral
    | Literal
    | SimpleVariableRef
    | BinaryExpr
    | XmlCommentLiteral
    | UnaryExpr
  >;
  endTagName?: XmlQname | SimpleVariableRef | Literal | BinaryExpr;
  inTemplateLiteral?: boolean;
  isExpression?: boolean;
  namespaces: string;
  position: any;
  root?: boolean;
  startLiteral?: string;
  startTagName: XmlQname | SimpleVariableRef | Literal | BinaryExpr;
  symbolType: string[];
  ws: any[];
}

export interface XmlPiLiteral extends ASTNode {
  dataTextFragments: Array<Literal | SimpleVariableRef>;
  isExpression?: boolean;
  position: any;
  root: boolean;
  startLiteral: string;
  symbolType: string[];
  target: Literal;
  ws: any[];
}

export interface XmlQname extends ASTNode {
  inTemplateLiteral?: boolean;
  localname: Identifier;
  position: any;
  prefix: Identifier;
  symbolType: string[];
  ws: any[];
}

export interface XmlQuotedString extends ASTNode {
  position: any;
  symbolType: string[];
  textFragments: Array<Literal | SimpleVariableRef | BinaryExpr>;
}

export interface XmlTextLiteral extends ASTNode {
  isExpression?: boolean;
  position: any;
  root: boolean;
  startLiteral: string;
  symbolType: string[];
  textFragments: Array<Literal | SimpleVariableRef>;
  ws: any[];
}

export interface Xmlns extends ASTNode {
  global?: boolean;
  namespaceDeclaration?: Xmlns;
  namespaceURI?: Literal;
  position: any;
  prefix?: Identifier;
  symbolType?: string[];
  ws?: any[];
}

// tslint:enable:ban-types
