blank_issues_enabled: false
contact_links:
  - name: General Question
    url: https://stackoverflow.com/questions/tagged/ballerina
    about: "If you have a question then please ask on Stack Overflow using the #ballerina tag."
  - name: Chat
    url: https://discord.com/invite/wAJYFbMrG2
    about: "Chat about anything else with the community."
