name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["Type/Bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give a brief description of the bug
    validations:
      required: true
  - type: textarea
    id: reproducing-steps
    attributes:
      label: Steps to Reproduce
      description: The steps to be followed to reproduce the issue.
    validations:
      required: false
  - type: textarea
    id: affected-area
    attributes:
      label: Affected Version(s)
      description: The versions that are affected by the bug
    validations:
      required: false
  - type: textarea
    id: env-details
    attributes:
      label: OS, DB, other environment details and versions
    validations:
      required: false
  - type: dropdown
    id: labels
    attributes:
      label: Related area
      description: Tag the issue with related area
      multiple: false
      options:
        - -> Compilation
        - -> Runtime
        - -> Standard Library
        - -> Central
        - -> Website
        - -> API Docs
        - -> Debugger
        - -> Update Tool
        - -> gRPC Tool
        - -> AsyncAPI Tool
        - -> OpenAPI Tool
        - -> SemVer Validator Tool
        - -> Bindgen Tool
        - -> Formatter
        - -> Shell
        - -> Editor
        - -> Test Framework
        - -> Observability
        - -> CICD
        - -> Other Area
    validations:
      required: true
  - type: textarea
    id: related-issues
    attributes:
      label: Related issue(s) (optional)
      description: Any related issues such as sub tasks and issues reported in other repositories (e.g., component repositories), similar problems, etc. 
    validations:
      required: false
  - type: textarea
    id: suggested-labels
    attributes:
      label: Suggested label(s) (optional)
      description: Optional comma-separated list of suggested labels. Non committers can’t assign labels to issues, and thereby, this will help issue creators who are not a committer to suggest possible labels.
    validations:
      required: false
  - type: textarea
    id: suggested-assignees
    attributes:
      label: Suggested assignee(s) (optional)
      description: Optional comma-separated list of suggested team members who should attend the issue. Non committers can’t assign issues to assignees, and thereby, this will help issue creators who are not a committer to suggest possible assignees.
    validations:
      required: false
