/*
 * Copyright (c) 2023, WSO2 LLC. (https://www.wso2.com) All Rights Reserved.
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.ballerinalang.test.observe.syntaxtree;

import org.ballerinalang.test.BCompileUtil;
import org.ballerinalang.test.CompileResult;
import org.testng.Assert;
import org.testng.annotations.Test;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.file.Paths;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * Test class to test the equality of the syntax tree generated by the ObservabilitySymbolCollector.
 *
 * @since 2201.6.0
 */
public class SyntaxTreeEqualityTest {

    private static final String testPkgLocation = "test-src/syntaxtree";

    @Test
    public void testSyntaxTreeEquality() throws URISyntaxException, IOException {
        String packageName = "syntaxtree";
        String jsonFilePath = Paths.get("syntax-tree", "syntax-tree.json").toFile().getPath();

        // Build the package
        CompileResult firstBuildResult = BCompileUtil.compile(testPkgLocation);
        URLClassLoader firstBuildClassLoader = (URLClassLoader) firstBuildResult.getClassLoader();
        URL[] firstBuildURLs = firstBuildClassLoader.getURLs();
        String firstBuildJarPath = null;

        for (URL url : firstBuildURLs) {
            String jarPath = new File(url.toURI()).getPath();
            if (jarPath.contains(packageName)) {
                firstBuildJarPath = jarPath;
            }
        }
        ZipFile firstBuildJar = new ZipFile(firstBuildJarPath);
        ZipEntry jsonFileEntry = firstBuildJar.getEntry(jsonFilePath);

        InputStream jsonFileInputStream = firstBuildJar.getInputStream(jsonFileEntry);
        String firstBuildJsonFileContent = new String(jsonFileInputStream.readAllBytes());

        // Build the package again
        CompileResult secondBuildResult = BCompileUtil.compile(testPkgLocation);
        URLClassLoader secondBuildClassLoader = (URLClassLoader) secondBuildResult.getClassLoader();
        URL[] secondBuildURLs = secondBuildClassLoader.getURLs();
        String secondBuildJarPath = null;

        for (URL url : secondBuildURLs) {
            String jarPath = new File(url.toURI()).getPath();
            if (jarPath.contains(packageName)) {
                secondBuildJarPath = jarPath;
            }
        }
        ZipFile secondBuildJar = new ZipFile(secondBuildJarPath);
        ZipEntry secondJsonFileEntry = secondBuildJar.getEntry(jsonFilePath);

        InputStream secondJsonFileInputStream = secondBuildJar.getInputStream(secondJsonFileEntry);
        String secondBuildJsonFileContent = new String(secondJsonFileInputStream.readAllBytes());

        // Compare the syntax trees
        Assert.assertEquals(secondBuildJsonFileContent, firstBuildJsonFileContent);
    }
}
