[package]
org = "ballerina"
name = "module1"
version = "0.1.0"

[[platform.java11.dependency]]
path = "../libs/language-server-stdlib-${version}.jar"
groupId = "ballerina"
artifactId = "mock"
version = "0.0.0"
