// This is an empty Ballerina object autogenerated to represent the `java.util.regex.Pattern` Java class.
//
// If you need the implementation of this class generated, please use the following command.
//
// $ ballerina bindgen [(-cp|--classpath) <classpath>...] [(-o|--output) <output>] (<class-name>...)
//
// E.g. $ ballerina bindgen java.util.regex.Pattern



# Ballerina object mapping for Java class `java/util/regex/Pattern`.
#
# + _Pattern - The field that represents this Ballerina object, which is used for Java subtyping.
# + _Serializable - The field that represents the superclass object `Serializable`.
# + _Object - The field that represents the superclass object `Object`.
type Pattern object {

    *JObject;

    PatternT _Pattern = PatternT;
    SerializableT _Serializable = SerializableT;
    ObjectT _Object = ObjectT;

    # The init function of the Ballerina object mapping `java/util/regex/Pattern` Java class.
    #
    # + obj - The `handle` value containing the Java reference of the object.
    function init(handle obj) {
        self.jObj = obj;
    }

    # The function to retrieve the string value of a Ballerina object mapping a Java class.
    #
    # + return - The `string` form of the object instance.
    function toString() returns string {
        return jObjToString(self.jObj);
    }
};


