/*
 * Copyright (c) 2021, WSO2 Inc. (http://wso2.com) All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.ballerinalang.debugadapter;

import org.eclipse.lsp4j.debug.OutputEventArguments;
import org.eclipse.lsp4j.debug.OutputEventArgumentsCategory;
import org.eclipse.lsp4j.debug.services.IDebugProtocolClient;

/**
 * Wrapper implementation for the DAP `client/output` endpoint, which can be used to send debug server and target VM
 * outputs to the debugger client side.
 *
 * @since 2.0.0
 */
public class DebugOutputLogger {

    private final IDebugProtocolClient client;
    private boolean isCompilationDone;

    private static final String COMPILER_LOG_RUNNING_EXECUTABLE = "Running executable";
    private static final String COMPILER_LOG_RUNNING_TESTS = "Running Tests";

    public DebugOutputLogger(IDebugProtocolClient client) {
        this.client = client;
    }

    /**
     * Processes messages that should be treated as the program output.
     *
     * @param output string output produced in the debugger/target VM.
     */
    public void sendProgramOutput(String output) {
        if (isInternalLog(output)) {
            return;
        }
        if (!output.endsWith(System.lineSeparator())) {
            output += System.lineSeparator();
        }
        OutputEventArguments outputEventArguments = new OutputEventArguments();
        outputEventArguments.setOutput(output);
        outputEventArguments.setCategory(OutputEventArgumentsCategory.STDOUT);
        client.output(outputEventArguments);
    }

    /**
     * Processes messages which are generated by the target VM and should treated as console outputs.
     *
     * @param output string output produced in the target VM.
     */
    public void sendConsoleOutput(String output) {
        if (isInternalLog(output)) {
            return;
        }
        if (!output.endsWith(System.lineSeparator())) {
            output += System.lineSeparator();
        }
        OutputEventArguments outputArguments = new OutputEventArguments();
        outputArguments.setOutput(output);
        // Since Ballerina compiler logs and errors are redirected to the same stream (STDERR) by design, output
        // category has to be derived based on the output prefix. Once the Ballerina program has reached to the
        // executable running state, there cannot be any compiler logs and hence the category should be "STDERR".
        if (isCompilationDone || containsBalErrorPrefix(output)) {
            outputArguments.setCategory(OutputEventArgumentsCategory.STDERR);
        } else {
            outputArguments.setCategory(OutputEventArgumentsCategory.CONSOLE);
        }
        client.output(outputArguments);

        if (output.startsWith(COMPILER_LOG_RUNNING_EXECUTABLE) || output.startsWith(COMPILER_LOG_RUNNING_TESTS)) {
            isCompilationDone = true;
        }
    }

    /**
     * Processes messages which are generated by the debug server itself and should treated as console outputs.
     *
     * @param output string output produced in the debugger/target VM.
     */
    public void sendDebugServerOutput(String output) {
        if (!output.endsWith(System.lineSeparator())) {
            output += System.lineSeparator();
        }
        OutputEventArguments outputArguments = new OutputEventArguments();
        outputArguments.setOutput(output);
        outputArguments.setCategory(OutputEventArgumentsCategory.CONSOLE);
        client.output(outputArguments);
    }

    /**
     * Processes messages which should treated as the error output.
     *
     * @param output string output produced in the debugger/target VM.
     */
    public void sendErrorOutput(String output) {
        if (isInternalLog(output)) {
            return;
        }
        if (!output.endsWith(System.lineSeparator())) {
            output += System.lineSeparator();
        }
        OutputEventArguments outputEventArguments = new OutputEventArguments();
        outputEventArguments.setOutput(output);
        outputEventArguments.setCategory(OutputEventArgumentsCategory.STDERR);
        client.output(outputEventArguments);
    }

    private static boolean containsBalErrorPrefix(String output) {
        // Todo: Add more error patterns
        return output.startsWith("ERROR") || output.startsWith("error:");
    }

    private static boolean isInternalLog(String output) {
        return output.startsWith("Listening for transport dt_socket")
                || output.startsWith("Please start the remote debugging client to continue")
                || output.startsWith("JAVACMD")
                || output.startsWith("Stream closed");
    }
}
