CREATE TABLE IF NOT EXISTS SALARY (
  ID INTEGER,
  AMOUNT DOUBLE
);
/
CREATE TABLE IF NOT EXISTS SalaryTrx (
  ID INTEGER,
  AMOUNT DOUBLE,
  PRIMARY KEY (ID)
);
/
INSERT INTO SalaryTrx VALUES (20, 30000);
/