plugins {
    id 'javaProject'
}

group = 'org.ballerinalang'
version = '2201.14.0-SNAPSHOT'

repositories {
    mavenCentral()
}

jar {
    dependsOn configurations.runtimeClasspath
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    manifest {
        attributes(
                'Implementation-Title': 'OCI Client',
                'Implementation-Version': version
        )
    }
    from({ configurations.runtimeClasspath.collect { it.isDirectory() ? it : zipTree(it) } }) {
        exclude 'module-info.class'
        exclude 'META-INF/versions/*/module-info.class'
    }
}

dependencies {
    implementation project(':central-client')
    implementation libs.squareup.okhttp
    implementation libs.jib.core
    implementation libs.apache.commons.compress
    implementation 'com.google.http-client:google-http-client:1.42.2'
    implementation libs.tongfei.progressbar
    implementation 'com.google.code.gson:gson:2.10.1'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}

ext.moduleName = 'org.ballerinalang.oci'

compileJava {
    inputs.property("moduleName", moduleName)
    doFirst {
        options.compilerArgs << '--module-path' << classpath.asPath
        classpath = files()
    }
}

javadoc {
    doFirst {
        options.modulePath = classpath.toList()
        classpath = files()
    }
}

