package org.ballerinalang.format;

/**
 * Class to hold the messages generated by the Formatting CLI tool.
 */
public class Messages {
    private static final String ARGUMENT_ERROR = "too many arguments.\n"
            + "ex: ballerina format [ballerinaFile|ModuleName] [-ow|--over-write]";
    private static final String CONFIRMATION_MESSAGE = "info: this will replace the content of the original file." +
            "\ndo you like to proceed? (y/n): ";
    private static final String SUCCESS_MESSAGE = "info: format Successful.\n File: ";

    private static final String CANCEL_MESSAGE = "info: formatting process canceled.";

    private static final String NOT_BALLERINA_PROJECT = "not a Ballerina project directory.";

    private static final String NO_MODULE_FOUND = "couldn't find a existing module by the name: ";

    private static final String EXCEPTION = "something went wrong when formatting.\n";

    private static final String NO_BALLERINA_FILE = "couldn't find a existing ballerina file by the name: ";

    private static final String NOT_BALLERINA_FILE = "not a ballerina source file.";

    private static final String NO_BALLERINA_FILE_OR_MODULE = "couldn't find a existing ballerina file or " +
            "module by the name: ";

    static String getArgumentError() {
        return ARGUMENT_ERROR;
    }

    static String getConfirmationMessage() {
        return CONFIRMATION_MESSAGE;
    }

    static String getSuccessMessage(String fileName) {
        return SUCCESS_MESSAGE + fileName;
    }

    static String getCancelMessage() {
        return CANCEL_MESSAGE;
    }

    static String getNotBallerinaProject() {
        return NOT_BALLERINA_PROJECT;
    }

    static String getNoModuleFound(String moduleName) {
        return NO_MODULE_FOUND + moduleName;
    }

    static String getException() {
        return EXCEPTION;
    }

    static String getNoBallerinaFile(String fileName) {
        return NO_BALLERINA_FILE + fileName;
    }

    static String getNoBallerinaModuleOrFile(String fileName) {
        return NO_BALLERINA_FILE_OR_MODULE + fileName;
    }

    static String getNotABallerinaFile() {
        return NOT_BALLERINA_FILE;
    }
}
