// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloWorld.proto

package org.ballerinalang.test.util.grpc.client.helloworld;

public final class HelloServiceProto {
    private HelloServiceProto() {
    }
    
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }
    
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    
    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    
    static {
        String[] descriptorData = {
                "\n\020helloWorld.proto\032\036google/protobuf/wrap" +
                        "pers.proto2Q\n\nhelloWorld\022C\n\005hello\022\034.goog" +
                        "le.protobuf.StringValue\032\034.google.protobu" +
                        "f.StringValueB;\n\036org.wso2.msf4j.grpc.hel" +
                        "loworldB\021HelloServiceProtoP\001\242\002\003HLWb\006prot" +
                        "o3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                                com.google.protobuf.WrappersProto.getDescriptor(),
                        }, assigner);
        com.google.protobuf.WrappersProto.getDescriptor();
    }
}
