annotation Foo on type,
                  class,
                  function,
                  object function,
                  service remote function,
                  parameter,
                  return,
                  service,
                  field,
                  object field,
                  record field,
                  source type,
                  source class,
                  source function,
                  source object function,
                  source service remote function,
                  source parameter,
                  source return,
                  source service,
                  source field,
                  source object field,
                  source record field,
                  source annotation,
                  source external,
                  source var,
                  source const,
                  source listener,
                  source worker;
