annotation Foo on source parameter,
                  parameter,
                  type,
                  source object type,
                  object function,
                  resource function,
                  function,
                  object field,
                  source record field,
                  source annotation,
                  source var;
