
  var constants = {
      STRUCT_DEFINITION_ATTRIBUTES_ARRAY_NAME: 'name',
      STRUCT_DEFINITION_ATTRIBUTES_ARRAY_PROPERTIES: 'properties',
      STRUCT_DEFINITION_ATTRIBUTES_ARRAY_PROPERTY_NAME: 'name',
      STRUCT_DEFINITION_ATTRIBUTES_ARRAY_PROPERTY_TYPE: 'type',
      TYPE_MAPPER_COMBOBOX_DEFAULT_SELECTION: '--Select--',
      TYPE_MAPPER_COMBOBOX_PREVIOUS_SELECTION: 'previousStructSelection',
      TYPE_MAPPER_COMBOBOX_SOURCE_IS_ALREADY_RENDERED_IN_TARGET: 'tmRenderedInTarget',
      TYPE_MAPPER_COMBOBOX_TARGET_IS_ALREADY_RENDERED_IN_SOURCE: 'tmRenderedInSource',
      TYPE_MAPPER_SOURCE_STRUCT_NAME: 'sourceStructName',
      TYPE_MAPPER_SOURCE_STRUCT_SCHEMA: 'sourceStruct',
      TYPE_MAPPER_TARGET_STRUCT_NAME: 'targetStructName',
      TYPE_MAPPER_TARGET_STRUCT_SCHEMA: 'targetStruct'
  };

  export default constants;

