var STRUCT_DEFINITION_ATTRIBUTES_ARRAY_NAME = 'name';
var STRUCT_DEFINITION_ATTRIBUTES_ARRAY_PROPERTIES = 'properties';
var STRUCT_DEFINITION_ATTRIBUTES_ARRAY_PROPERTY_NAME = 'name';
var STRUCT_DEFINITION_ATTRIBUTES_ARRAY_PROPERTY_TYPE = 'type';
var TYPE_MAPPER_COMBOBOX_DEFAULT_SELECTION = '--Select--';
var TYPE_MAPPER_COMBOBOX_PREVIOUS_SELECTION = 'previousStructSelection';
