package io.ballerina.cli.cmd;

import io.ballerina.cli.BLauncherCmd;
import io.ballerina.cli.TaskExecutor;
import io.ballerina.cli.launcher.BLauncherException;
import io.ballerina.cli.task.CleanTargetDirTask;
import io.ballerina.cli.task.CompileTask;
import io.ballerina.cli.task.CreateBalaTask;
import io.ballerina.cli.task.DumpBuildTimeTask;
import io.ballerina.cli.task.ResolveMavenDependenciesTask;
import io.ballerina.cli.task.RunBuildToolsTask;
import io.ballerina.cli.utils.BuildTime;
import io.ballerina.cli.utils.FileUtils;
import io.ballerina.projects.BuildOptions;
import io.ballerina.projects.DependencyGraph;
import io.ballerina.projects.DiagnosticResult;
import io.ballerina.projects.PackageDescriptor;
import io.ballerina.projects.Project;
import io.ballerina.projects.ProjectException;
import io.ballerina.projects.ProjectKind;
import io.ballerina.projects.ProjectLoadResult;
import io.ballerina.projects.ResolvedPackageDependency;
import io.ballerina.projects.directory.BuildProject;
import io.ballerina.projects.directory.ProjectLoader;
import io.ballerina.projects.directory.WorkspaceProject;
import io.ballerina.projects.environment.PackageLockingMode;
import io.ballerina.projects.internal.ProjectDiagnosticErrorCode;
import io.ballerina.projects.util.ProjectConstants;
import io.ballerina.projects.util.ProjectPaths;
import io.ballerina.projects.util.ProjectUtils;
import io.ballerina.projects.util.TomlUtil;
import io.ballerina.toml.semantic.TomlType;
import io.ballerina.toml.semantic.ast.TomlTableNode;
import io.ballerina.toml.semantic.ast.TopLevelNode;
import io.ballerina.tools.diagnostics.Diagnostic;
import org.wso2.ballerinalang.util.RepoUtils;
import picocli.CommandLine;

import java.io.IOException;
import java.io.PrintStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static io.ballerina.cli.cmd.Constants.PACK_COMMAND;
import static io.ballerina.projects.internal.ManifestBuilder.getStringValueFromTomlTableNode;
import static io.ballerina.runtime.api.constants.RuntimeConstants.SYSTEM_PROP_BAL_DEBUG;

/**
 * This class represents the "bal pack" command.
 *
 * @since 2.0.0
 */
@CommandLine.Command(name = PACK_COMMAND, description = "Create distribution format of the current package")
public class PackCommand implements BLauncherCmd {

    private final PrintStream outStream;
    private final PrintStream errStream;
    private final boolean exitWhenFinish;
    private final boolean skipCopyLibsFromDist;

    @CommandLine.Option(names = {"--offline"}, description = "Build/Compile offline without downloading " +
            "dependencies.")
    private Boolean offline;

    @CommandLine.Parameters (arity = "0..1")
    private final Path projectPath;

    @CommandLine.Option(names = "--dump-bir", hidden = true)
    private boolean dumpBIR;

    @CommandLine.Option(names = "--dump-bir-file", hidden = true)
    private Boolean dumpBIRFile;

    @CommandLine.Option(names = "--dump-graph", hidden = true)
    private boolean dumpGraph;

    @CommandLine.Option(names = "--dump-raw-graphs", hidden = true)
    private boolean dumpRawGraphs;

    @CommandLine.Option(names = {"--help", "-h"}, hidden = true)
    private boolean helpFlag;

    @CommandLine.Option(names = "--experimental", description = "Enable experimental language features.")
    private Boolean experimentalFlag;

    @CommandLine.Option(names = "--debug", description = "run tests in remote debugging mode")
    private String debugPort;

    @CommandLine.Option(names = "--dump-build-time", hidden = true, description = "calculate and dump build time")
    private Boolean dumpBuildTime;

    @CommandLine.Option(names = "--sticky", description = "stick to exact versions locked (if exists)")
    private Boolean sticky;

    @CommandLine.Option(names = "--target-dir", description = "target directory path")
    private Path targetDir;

    @CommandLine.Option(names = "--generate-config-schema", hidden = true)
    private Boolean configSchemaGen;

    @CommandLine.Option(names = "--disable-syntax-tree-caching", hidden = true, description = "disable syntax tree " +
            "caching for source files", defaultValue = "false")
    private Boolean disableSyntaxTreeCaching;

    @CommandLine.Option(names = "--show-dependency-diagnostics", description = "Show the diagnostics " +
            "generated by the dependencies")
    private Boolean showDependencyDiagnostics;

    @CommandLine.Option(names = "--optimize-dependency-compilation", hidden = true,
            description = "experimental memory optimization for large projects")
    private Boolean optimizeDependencyCompilation;

    @CommandLine.Option(names = "--locking-mode", hidden = true,
            description = "allow passing the package locking mode.", converter = PackageLockingModeConverter.class)
    private PackageLockingMode lockingMode;

    @CommandLine.Option(names = "--repair-on-failure", hidden = true,
            description = "If the workspace build fails due to dependency version conflicts, " +
                          "retry the build with soft locking mode. Ignored for standalone packages.")
    private Boolean repairOnFailure;

    @CommandLine.Option(names = "--skip-sbom", hidden = true,
            description = "skip SBOM generation and pack the bala without it")
    private Boolean skipSbom;

    public PackCommand() {
        this.projectPath = Path.of(System.getProperty(ProjectConstants.USER_DIR));
        this.outStream = System.out;
        this.errStream = System.err;
        this.exitWhenFinish = true;
        this.skipCopyLibsFromDist = false;
    }

    PackCommand(Path projectPath, PrintStream outStream, PrintStream errStream, boolean exitWhenFinish,
                       boolean skipCopyLibsFromDist) {
        this.projectPath = projectPath;
        this.outStream = outStream;
        this.errStream = errStream;
        this.exitWhenFinish = exitWhenFinish;
        this.skipCopyLibsFromDist = skipCopyLibsFromDist;
        this.offline = true;
    }

    PackCommand(Path projectPath, PrintStream outStream, PrintStream errStream, boolean exitWhenFinish,
                boolean skipCopyLibsFromDist, Boolean optimizeDependencyCompilation) {
        this.projectPath = projectPath;
        this.outStream = outStream;
        this.errStream = errStream;
        this.exitWhenFinish = exitWhenFinish;
        this.skipCopyLibsFromDist = skipCopyLibsFromDist;
        this.optimizeDependencyCompilation = optimizeDependencyCompilation;
        this.offline = true;
    }

    PackCommand(Path projectPath, PrintStream outStream, PrintStream errStream, boolean exitWhenFinish,
                       boolean skipCopyLibsFromDist, Path targetDir) {
        this.projectPath = projectPath;
        this.outStream = outStream;
        this.errStream = errStream;
        this.exitWhenFinish = exitWhenFinish;
        this.skipCopyLibsFromDist = skipCopyLibsFromDist;
        this.targetDir = targetDir;
        this.offline = true;
    }

    @Override
    public void execute() {
        int exitCode = 0;
        long start = 0;

        if (this.helpFlag) {
            String commandUsageInfo = BLauncherCmd.getCommandUsageInfo(PACK_COMMAND);
            this.errStream.println(commandUsageInfo);
            return;
        }

        Project project;
        Path absProjectPath = this.projectPath.toAbsolutePath().normalize();
        BuildOptions buildOptions = constructBuildOptions();
        DiagnosticResult diagnosticResult;

        // Throw an error if its a single file
        if (FileUtils.hasExtension(this.projectPath)) {
            CommandUtil.printError(this.errStream, "bal pack can only be used with a Ballerina package.", null, false);
            CommandUtil.exitError(this.exitWhenFinish);
            return;
        }

        try {
            if (buildOptions.dumpBuildTime()) {
                start = System.currentTimeMillis();
                BuildTime.getInstance().timestamp = start;
            }
            if (!ProjectPaths.isBuildProjectRoot(projectPath) && !ProjectPaths.isWorkspaceProjectRoot(projectPath)) {
                throw new ProjectException("invalid package path: " + absProjectPath +
                        ". Please provide a valid Ballerina package or a workspace.");
            }
            ProjectLoadResult loadResult = ProjectLoader.load(projectPath, buildOptions);
            diagnosticResult = loadResult.diagnostics();
            if (diagnosticResult.hasErrors()) {
                exitCode = 1;
            }
            project = loadResult.project();
            if (buildOptions.dumpBuildTime()) {
                BuildTime.getInstance().projectLoadDuration = System.currentTimeMillis() - start;
            }
        } catch (ProjectException e) {
            CommandUtil.printError(this.errStream, e.getMessage(), null, false);
            CommandUtil.exitError(this.exitWhenFinish);
            return;
        }

        // Check `[package]` section is available when compile
        if (project.currentPackage().ballerinaToml().get().tomlDocument().toml().getTable("package")
                .isEmpty()) {
            CommandUtil.printError(this.errStream,
                    "'package' information not found in " + ProjectConstants.BALLERINA_TOML,
                    null,
                    false);
            CommandUtil.exitError(this.exitWhenFinish);
            return;
        } else {
            // if not empty, validate the `[package]` section

            TomlTableNode pkgNode = (TomlTableNode) project.currentPackage().ballerinaToml().get().tomlDocument().toml()
                    .rootNode().entries().get("package");
            if (pkgNode == null || pkgNode.kind() == TomlType.NONE) {
                CommandUtil.printError(this.errStream,
                        "'package' information not found in " + ProjectConstants.BALLERINA_TOML,
                        null,
                        false);
                CommandUtil.exitError(this.exitWhenFinish);
                return;
            }

            List<String> pkgErrors = new ArrayList<>();
            if ("".equals(getStringValueFromTomlTableNode(pkgNode, "org", ""))) {
                pkgErrors.add("'org'");
            }
            if ("".equals(getStringValueFromTomlTableNode(pkgNode, "name", ""))) {
                pkgErrors.add("'name'");
            }
            if ("".equals(getStringValueFromTomlTableNode(pkgNode, "version", ""))) {
                pkgErrors.add("'version'");
            }

            if (!pkgErrors.isEmpty()) {
                String pkgErrorsString;
                if (pkgErrors.size() == 1) {
                    CommandUtil.printError(this.errStream,
                            "to build a package " + pkgErrors.get(0) +
                                    " field of the package is required in " +
                                    ProjectConstants.BALLERINA_TOML,
                            null,
                            false);
                    CommandUtil.exitError(this.exitWhenFinish);
                    return;
                } else if (pkgErrors.size() == 2) {
                    pkgErrorsString = pkgErrors.get(0) + " and " + pkgErrors.get(1);
                } else {
                    pkgErrorsString = pkgErrors.get(0) + ", " + pkgErrors.get(1) + " and " + pkgErrors.get(2);
                }
                CommandUtil.printError(this.errStream,
                        "to build a package " + pkgErrorsString +
                                " fields of the package are required in " +
                                ProjectConstants.BALLERINA_TOML,
                        null,
                        false);
                CommandUtil.exitError(this.exitWhenFinish);
                return;
            }

        }

        // Sets the debug port as a system property, which will be used when setting up debug args before running tests.
        if (!project.buildOptions().skipTests() && this.debugPort != null) {
            System.setProperty(SYSTEM_PROP_BAL_DEBUG, this.debugPort);
        }

        // Validate Settings.toml file
        RepoUtils.readSettings();

        if (project.kind() == ProjectKind.WORKSPACE_PROJECT) {
            diagnosticResult.diagnostics().forEach(diagnostic -> this.errStream.println(diagnostic.toString()));
            WorkspaceProject workspaceProject = (WorkspaceProject) project;
            if (workspaceProject.sourceRoot().equals(absProjectPath)) {
                executeWorkspaceFromRoot(workspaceProject, buildOptions);
            } else {
                executeWorkspaceFromProjectPath(workspaceProject, absProjectPath, buildOptions);
            }
        } else {
            // Check package files are modified after last build
            Optional<Diagnostic> deprecatedDocWarning = ProjectUtils.getProjectLoadingDiagnostic().stream().filter(
                    diagnostic -> diagnostic.diagnosticInfo().code().equals(
                            ProjectDiagnosticErrorCode.DEPRECATED_DOC_FILE.diagnosticId())).findAny();
            deprecatedDocWarning.ifPresent(this.errStream::println);
            executeTasks(project);
        }

        if (this.exitWhenFinish) {
            Runtime.getRuntime().exit(exitCode);
        }
    }

    private void executeTasks(Project project) {
        List<Diagnostic> buildToolDiagnostics = new ArrayList<>();
        TaskExecutor taskExecutor = new TaskExecutor.TaskBuilder()
                .addTask(new CleanTargetDirTask())
                .addTask(new RunBuildToolsTask(outStream, false, buildToolDiagnostics))
                .addTask(new ResolveMavenDependenciesTask(outStream))
                .addTask(new CompileTask(outStream, errStream, true, false, false, buildToolDiagnostics))
                .addTask(new CreateBalaTask(outStream))
                .addTask(new DumpBuildTimeTask(outStream), !project.buildOptions().dumpBuildTime())
                .build();
        taskExecutor.executeTasks(project);
    }

    private void executeWorkspaceFromRoot(WorkspaceProject workspaceProject, BuildOptions buildOptions) {
        executeWorkspaceFromRoot(workspaceProject, buildOptions, false);
    }

    private void executeWorkspaceFromRoot(WorkspaceProject workspaceProject, BuildOptions buildOptions,
                                          boolean isRecovery) {
        // Phase 1: Execute build tools for all projects
        boolean hasAnyTools = workspaceProject.projects().stream()
                .anyMatch(p -> !p.currentPackage().manifest().tools().isEmpty());
        if (hasAnyTools) {
            this.outStream.println("Executing Build Tools");
        }
        Map<Path, List<Diagnostic>> buildToolDiagnosticsMap = new HashMap<>();
        for (BuildProject buildProject : workspaceProject.projects()) {
            List<Diagnostic> diagnostics = executeBuildToolsTask(buildProject);
            buildToolDiagnosticsMap.put(buildProject.sourceRoot(), diagnostics);
        }

        // Resolve workspace dependencies (after build tools, so generated code is visible)
        DependencyGraph<BuildProject> projectDependencyGraph = CommandUtil.resolveWorkspaceDependencies(
                workspaceProject, this.outStream);
        List<BuildProject> topologicallySortedList = new ArrayList<>(
                projectDependencyGraph.toTopologicallySortedList());

        // Phase 2: Execute remaining tasks in topological order
        List<BuildProject> successfullyBuilt = new ArrayList<>();
        BuildProject failedProject = null;
        try {
            for (BuildProject buildProject : topologicallySortedList) {
                List<Diagnostic> buildToolDiags = buildToolDiagnosticsMap.getOrDefault(
                        buildProject.sourceRoot(), new ArrayList<>());
                failedProject = buildProject;
                executeRemainingTasks(buildProject, buildToolDiags);
                successfullyBuilt.add(buildProject);
                failedProject = null;
            }
        } catch (BLauncherException e) {
            if (!isRecovery
                    && isRepairOnFailureEnabled(workspaceProject)
                    && hasMultipleVersions(successfullyBuilt, failedProject)) {
                outStream.println("WARNING: Build failed due to version conflicts across workspace " +
                        "dependencies. Updating the dependency versions and rebuilding the workspace...");
                BuildOptions recoveryOptions = repairedRecoveryOptions(buildOptions);
                cleanTargetDirs(successfullyBuilt, failedProject);
                WorkspaceProject recoveredProject = (WorkspaceProject)
                        ProjectLoader.load(workspaceProject.sourceRoot(), recoveryOptions).project();
                executeWorkspaceFromRoot(recoveredProject, recoveryOptions, true);
            } else {
                throw e;
            }
        }
    }

    private void executeWorkspaceFromProjectPath(WorkspaceProject workspaceProject, Path absProjectPath,
                                                  BuildOptions buildOptions) {
        executeWorkspaceFromProjectPath(workspaceProject, absProjectPath, buildOptions, false);
    }

    private void executeWorkspaceFromProjectPath(WorkspaceProject workspaceProject, Path absProjectPath,
                                                  BuildOptions buildOptions, boolean isRecovery) {
        // Initial resolution to find the target project (silent, no output)
        DependencyGraph<BuildProject> initialGraph = CommandUtil.resolveWorkspaceDependencies(
                workspaceProject);
        Optional<BuildProject> targetProjectOpt = initialGraph.getNodes().stream()
                .filter(node -> node.sourceRoot().equals(absProjectPath)).findFirst();
        BuildProject targetProject = targetProjectOpt.orElseThrow();

        // Phase 1: Execute build tools for target project only
        if (!targetProject.currentPackage().manifest().tools().isEmpty()) {
            this.outStream.println("Executing Build Tools");
        }
        List<Diagnostic> buildToolDiagnostics = executeBuildToolsTask(targetProject);

        // Re-resolve workspace dependencies (after build tools, so generated code is visible)
        DependencyGraph<BuildProject> resolvedGraph = CommandUtil.resolveWorkspaceDependencies(
                workspaceProject, this.outStream);
        Optional<BuildProject> resolvedTargetOpt = resolvedGraph.getNodes().stream()
                .filter(node -> node.sourceRoot().equals(absProjectPath)).findFirst();
        BuildProject resolvedTarget = resolvedTargetOpt.orElseThrow();

        // Phase 2: Execute remaining tasks for target project only
        try {
            executeRemainingTasks(resolvedTarget, buildToolDiagnostics);
        } catch (BLauncherException e) {
            List<BuildProject> allDependencies = new ArrayList<>(
                    resolvedGraph.getAllDependencies(resolvedTarget));
            if (!isRecovery
                    && isRepairOnFailureEnabled(workspaceProject)
                    && hasMultipleVersions(allDependencies, resolvedTarget)) {
                outStream.println("WARNING: Build failed due to version conflicts across workspace " +
                        "dependencies. Updating the dependency versions and rebuilding the workspace...");
                BuildOptions recoveryOptions = repairedRecoveryOptions(buildOptions);
                cleanTargetDirs(allDependencies, resolvedTarget);
                WorkspaceProject recoveredProject = (WorkspaceProject)
                        ProjectLoader.load(workspaceProject.sourceRoot(), recoveryOptions).project();
                executeWorkspaceFromProjectPath(recoveredProject, absProjectPath, recoveryOptions, true);
            } else {
                throw e;
            }
        }
    }

    private BuildOptions repairedRecoveryOptions(BuildOptions buildOptions) {
        BuildOptions recoveryOverride = BuildOptions.builder()
                .setSticky(false)
                .setLockingMode(PackageLockingMode.SOFT)
                .build();
        return buildOptions.acceptTheirs(recoveryOverride);
    }

    private void cleanTargetDirs(List<BuildProject> builtProjects, BuildProject failedProject) {
        List<BuildProject> projectsToClean = new ArrayList<>(builtProjects);
        if (failedProject != null) {
            projectsToClean.add(failedProject);
        }
        for (BuildProject project : projectsToClean) {
            Path targetDir = project.targetDir();
            if (Files.exists(targetDir)) {
                try (var paths = Files.walk(targetDir)) {
                    paths.sorted(Comparator.reverseOrder()).forEach(p -> {
                        try {
                            Files.delete(p);
                        } catch (IOException ignored) {
                        }
                    });
                } catch (IOException ignored) {
                }
            }
        }
    }

    /**
     * Returns true if the dependency graphs of the supplied projects (successfully built + the failed one, if any)
     * contain the same package (org/name) with two or more different versions across projects.
     * The failing project's graph is compared against the successfully built projects' graphs because a version
     * conflict between the failed project and its siblings is the primary workspace failure mode.
     */
    private boolean hasMultipleVersions(List<BuildProject> builtProjects, BuildProject failedProject) {
        Map<String, String> seenVersions = new HashMap<>();
        List<BuildProject> allProjects = new ArrayList<>(builtProjects);
        if (failedProject != null) {
            allProjects.add(failedProject);
        }
        for (BuildProject bp : allProjects) {
            for (ResolvedPackageDependency dep :
                    bp.currentPackage().getResolution().dependencyGraph().toTopologicallySortedList()) {
                PackageDescriptor desc = dep.packageInstance().descriptor();
                String key = desc.org().value() + "/" + desc.name().value();
                String version = desc.version().value().major() + "." + desc.version().value().minor()
                        + "." + desc.version().value().patch();
                String existing = seenVersions.putIfAbsent(key, version);
                if (existing != null && !existing.equals(version)) {
                    return true;
                }
            }
        }
        return false;
    }

    /**
     * Resolves if the workspace build recovery (soft-locking retry on version conflicts) is enabled.
     * The {@code --repair-on-failure} CLI flag wins if explicitly set; otherwise falls back to the
     * {@code [dependency-resolution].repairOnFailure} property in the workspace {@code Ballerina.toml}.
     */
    private boolean isRepairOnFailureEnabled(WorkspaceProject workspaceProject) {
        if (repairOnFailure != null) {
            return repairOnFailure;
        }
        TomlTableNode rootNode = workspaceProject.ballerinaToml().tomlAstNode();
        TopLevelNode depResNode = rootNode.entries().get("dependency-resolution");
        if (depResNode == null || depResNode.kind() != TomlType.TABLE) {
            return false;
        }
        return TomlUtil.getBooleanFromTableNode((TomlTableNode) depResNode, "repairOnFailure", false);
    }

    private List<Diagnostic> executeBuildToolsTask(BuildProject buildProject) {
        List<Diagnostic> buildToolDiagnostics = new ArrayList<>();
        TaskExecutor taskExecutor = new TaskExecutor.TaskBuilder()
                .addTask(new CleanTargetDirTask())
                .addTask(new RunBuildToolsTask(outStream, false, buildToolDiagnostics, true))
                .build();
        taskExecutor.executeTasks(buildProject);
        return buildToolDiagnostics;
    }

    private void executeRemainingTasks(BuildProject buildProject, List<Diagnostic> buildToolDiagnostics) {
        TaskExecutor taskExecutor = new TaskExecutor.TaskBuilder()
                .addTask(new ResolveMavenDependenciesTask(outStream))
                .addTask(new CompileTask(outStream, errStream, true, false, false, buildToolDiagnostics))
                .addTask(new CreateBalaTask(outStream))
                .addTask(new DumpBuildTimeTask(outStream), !buildProject.buildOptions().dumpBuildTime())
                .build();
        taskExecutor.executeTasks(buildProject);
    }

    private BuildOptions constructBuildOptions() {
        BuildOptions.BuildOptionsBuilder buildOptionsBuilder = BuildOptions.builder();
        buildOptionsBuilder
                .setExperimental(experimentalFlag)
                .setOffline(offline)
                .setDumpBir(dumpBIR)
                .setDumpBirFile(dumpBIRFile)
                .setDumpGraph(dumpGraph)
                .setDumpRawGraphs(dumpRawGraphs)
                .setDumpBuildTime(dumpBuildTime)
                .setSticky(sticky)
                .setConfigSchemaGen(configSchemaGen)
                .disableSyntaxTreeCaching(disableSyntaxTreeCaching)
                .setShowDependencyDiagnostics(showDependencyDiagnostics)
                .setOptimizeDependencyCompilation(optimizeDependencyCompilation)
                .setLockingMode(lockingMode)
                .setSkipSbom(skipSbom);

        if (targetDir != null) {
            buildOptionsBuilder.targetDir(targetDir.toString());
        }

        return buildOptionsBuilder.build();
    }

    @Override
    public String getName() {
        return PACK_COMMAND;
    }

    @Override
    public void printLongDesc(StringBuilder out) {
        out.append(BLauncherCmd.getCommandUsageInfo(PACK_COMMAND));

    }

    @Override
    public void printUsage(StringBuilder out) {
        out.append("  bal pack [--offline] \\n\" +\n" + "            \"       [<package-path>]");
    }

    @Override
    public void setParentCmdParser(CommandLine parentCmdParser) {
    }
}
