name: TEMPORARY OOM CHECK

on:
  pull_request:
    branches:
      - master
      - nutcracker
jobs:
  ubuntu_build:
    name: Build with possible OOM test on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 150
    concurrency:
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.3'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :jballerina-integration-test:test 
          -Pnative.test --max-workers=2 --scan --no-daemon

      - name: Upload heap dump
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: heap-dump
          path: ./**/java_pid*.hprof
