name: Publish release

on:
  workflow_dispatch:

jobs:
  publish-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.3'
      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.3'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'false'
      - name: Set version env variable
        run: |
          VERSION=$(grep '^version=' gradle.properties | cut -d= -f2 | sed 's@-SNAPSHOT@@' | tr -d '[:space:]')
          if [ -z "${VERSION}" ]; then
            echo "VERSION is empty"; exit 1
          fi
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

          UPDATE_LEVEL=$(grep '^updateLevel=' gradle.properties | cut -d= -f2 | tr -d '[:space:]')
          if [ -z "${UPDATE_LEVEL}" ]; then
            UPDATE_LEVEL=0
          fi
          echo "UPDATE_LEVEL=${UPDATE_LEVEL}" >> $GITHUB_ENV
          if [[ "${UPDATE_LEVEL}" =~ ^[0-9]+$ ]] && [ "${UPDATE_LEVEL}" -gt 0 ]; then
            echo "RELEASE_VERSION=${VERSION}.${UPDATE_LEVEL}" >> $GITHUB_ENV
          else
            echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV
          fi
          echo "Using VERSION=${VERSION}, UPDATE_LEVEL=${UPDATE_LEVEL}"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Publish artifact
        env:
          publishUser: ${{ secrets.BALLERINA_BOT_USERNAME }}
          publishPAT: ${{ secrets.BALLERINA_BOT_TOKEN }}
#          publishRepository: ${{ github.repository }}
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          git config user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
          git config user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
          git checkout -b release-${RELEASE_VERSION}
          ./gradlew build -x :jballerina-debugger-integration-test:test -Pversion=${VERSION} -PupdateLevel=${UPDATE_LEVEL}
          ./gradlew publish -Pversion=${VERSION} -PupdateLevel=${UPDATE_LEVEL} -x test --continue
      - name: Create Release Tag
        run: |
          git config --local user.name ${{ secrets.BALLERINA_BOT_USERNAME }}
          git config --local user.email ${{ secrets.BALLERINA_BOT_EMAIL }}
          git tag -a v${RELEASE_VERSION} -m "Release v${RELEASE_VERSION}"
          git push origin v${RELEASE_VERSION}
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
      - name: Create Github release from the release tag
        run: |
          curl --request POST 'https://api.github.com/repos/ballerina-platform/ballerina-lang/releases' \
          --header 'Accept: application/vnd.github.v3+json' \
          --header 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
          --header 'Content-Type: application/json' \
          --data-raw '{
              "tag_name": "v'"$RELEASE_VERSION"'",
              "name": "ballerina-lang-v'"$RELEASE_VERSION"'"
          }'
      - name: Post release PR
        env:
          GITHUB_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          bin/hub pull-request -m "[Automated] Sync master after "$RELEASE_VERSION" release"
