name: CI Debugger Tests

on:
  pull_request:
    branches:
      - testerina-migration
      - master
      - next-release
      - release-stage
      - stage
      - ballerina-1.2.x
      - stage-swan-lake
      - 2201.[0-9]+.x
      - 2201.[0-9]+.[0-9]+-stage
      - native-build
      - revert-client-decl-master
      - query-grouping-aggregation

jobs:
  ubuntu_build:
    name: Running debugger integration tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 150
    concurrency:
      group: ${{ github.head_ref }}-ubuntu-debugger
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.3'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.3'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'false'

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :jballerina-debugger-integration-test:test -Pnative.test --max-workers=2 --scan --no-daemon
  windows_build:
    name: Running debugger integration tests on Windows
    runs-on: windows-latest
    timeout-minutes: 240
    concurrency: 
      group: ${{ github.head_ref }}-windows-debugger
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.3'

      - name: configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.4
        with:
          minimum-size: 8GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.3'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'false'

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew.bat :jballerina-debugger-integration-test:test --stacktrace -scan --console=plain --no-daemon --no-parallel


