name: 1.2.x Build without Tests

on: pull_request

jobs:
    ubuntu-build:
        name: Ubuntu
        concurrency:
            group: ${{ github.head_ref }}-ubuntu-build
            cancel-in-progress: true
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup JDK
              uses: actions/setup-java@v2
              with:
                distribution: 'temurin'
                java-version: 8
                check-latest: true

            -   name: Initialize Submodules
                run: |
                    git submodule update --init

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '10.22.1'
                  
            - name: Gradle Version
              run: |
                  ./gradlew -v

            - name: Build
              run: |                  
                  ./gradlew clean build -x test -x createJavadoc --stacktrace -scan --console=plain --no-daemon

    windows-build:
        name: Windows
        concurrency:
            group: ${{ github.head_ref }}-windows-build
            cancel-in-progress: true
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup JDK
              uses: actions/setup-java@v2
              with:
                  distribution: 'temurin'
                  java-version: 8

            -   name: Initialize Submodules
                run: |
                    git submodule update --init

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '10.22.1'

            - name: Build
              run: |
                  ./gradlew.bat clean build -x test -x createJavadoc --stacktrace -scan --console=plain --no-daemon
