name: CI Ubuntu

on:
  workflow_dispatch:

jobs:
  ubuntu_build:
    name: Build with all tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 150
    concurrency:
      group: ${{ github.head_ref }}-ubuntu
      cancel-in-progress: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21.0.3'

      - name: Initialize sub-modules
        run: git submodule update --init

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ github.sha }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21.0.3'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          set-java-home: 'false'

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export DISPLAY=':99.0'
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          ./gradlew :testerina:testerina-runtime:build --max-workers=2 --scan --no-daemon
          ./gradlew :testerina-integration-test:test --max-workers=2 --scan --no-daemon

      - name: Generate Jacoco report
        if: github.event_name == 'pull_request'
        run: ./gradlew createCodeCoverageReport

      - name: Generate Codecov Report
        if: github.event_name == 'pull_request'
        uses: codecov/codecov-action@v4
        with:
          files: ./.jacoco/reports/jacoco/report.xml


